SIMULINK_A7DAC: TF_PLL Class Reference
TF_PLL Class Reference
Управление синтезатором
#include <tf_dac.h>
Public Member Functions
TF_PLL (CL_Reg *reg)
virtual ~TF_PLL ()
void Prepare (void)
Подготовка PLL.
TF_PLL (CL_Reg *reg)
virtual ~TF_PLL ()
void Prepare (void)
Подготовка PLL.
int SetPll (double freq, double *pFreqOut)
Установка тактовой частоты
void SpdWrite (unsigned int adr, unsigned int data)
Запись в регистр синтезатора
void SetDiv (int divA, int divB)
Установка делителей
double GetFreq (int n)
Установленное значение частоты
Private Attributes
TF_PLL_TaskData * td
Внутренние данные класса
Detailed Description
Управление синтезатором
Definition at line 15 of file tf_dac.h.
Constructor & Destructor Documentation
TF_PLL() [1/2]
TF_PLL::TF_PLL (CL_Reg * reg)
Definition at line 29 of file tf_pll.cpp.
References TF_PLL_TaskData::divA, TF_PLL_TaskData::divB, TF_PLL_TaskData::reg, and td.
~TF_PLL() [1/2]
TF_PLL::~TF_PLL () virtual
Definition at line 39 of file tf_pll.cpp.
References td.
TF_PLL() [2/2]
TF_PLL::TF_PLL (CL_Reg * reg)
~TF_PLL() [2/2]
virtual TF_PLL::~TF_PLL () virtual
Member Function Documentation
GetFreq()
double TF_PLL::GetFreq (int n)
Установленное значение частоты
Definition at line 291 of file tf_pll.cpp.
References TF_PLL_TaskData::freqClkA, TF_PLL_TaskData::freqClkB, TF_PLL_TaskData::freqSynt, and td.
Referenced by TF_A7DacCtrl::EventStartCycle(), and TF_A7DacCtrl::Prepare().
Prepare() [1/2]
void TF_PLL::Prepare (void)
Подготовка PLL.
Prepare() [2/2]
void TF_PLL::Prepare (void)
Подготовка PLL.
Definition at line 46 of file tf_pll.cpp.
References CL_Reg::PkgCmdExecute(), CL_Reg::PkgCmdRead(), CL_Reg::PkgCmdStart(), CL_Reg::PkgCmdWrite(), TF_PLL_TaskData::reg, and td.
Referenced by TF_A7DacCtrl::Prepare().
SetDiv()
void TF_PLL::SetDiv (int divA, int divB)
Установка делителей
Definition at line 256 of file tf_pll.cpp.
References TF_PLL_TaskData::divA, TF_PLL_TaskData::divB, TF_PLL_TaskData::freqClkA, TF_PLL_TaskData::freqClkB, TF_PLL_TaskData::freqSynt, CL_Reg::PkgCmdExecute(), CL_Reg::PkgCmdStart(), CL_Reg::PkgCmdWrite(), TF_PLL_TaskData::reg, and td.
Referenced by TF_A7DacCtrl::Prepare().
SetPll()
int TF_PLL::SetPll (double freq, double * pFreqOut)
Установка тактовой частоты
Definition at line 97 of file tf_pll.cpp.
References TF_PLL_TaskData::divA, TF_PLL_TaskData::divB, TF_PLL_TaskData::freqClkA, TF_PLL_TaskData::freqClkB, TF_PLL_TaskData::freqSynt, CL_Reg::PkgCmdExecute(), CL_Reg::PkgCmdStart(), TF_PLL_TaskData::reg, SpdWrite(), and td.
Referenced by TF_A7DacCtrl::Prepare().
SpdWrite()
void TF_PLL::SpdWrite (unsigned int adr, unsigned int data)
Запись в регистр синтезатора
Definition at line 248 of file tf_pll.cpp.
References CL_Reg::PkgCmdWrite(), TF_PLL_TaskData::reg, and td.
Referenced by SetPll().
Member Data Documentation
td
TF_PLL_TaskData * TF_PLL::td private
Внутренние данные класса
Definition at line 18 of file tf_dac.h.
Referenced by GetFreq(), Prepare(), SetDiv(), SetPll(), SpdWrite(), TF_PLL(), and ~TF_PLL().
The documentation for this class was generated from the following files:
E:/_github/simulink_sm/simulink_a7dac/src/work/tf_dac.h
E:/_github/simulink_sm/simulink_a7dac/src/work/tf_pll.h
E:/_github/simulink_sm/simulink_a7dac/src/work/tf_pll.cpp