SM_ADC: Output ports managing methods
Output ports managing methods
Functions
static void BaseBlock::setOutputDouble (int port, double value)
static void BaseBlock::setOutputArray (int port, Array &array)
static Array BaseBlock::getOutputArray (int port)
static int BaseBlock::getOutputWidth (int port)
static int BaseBlock::getOutputNRows (int port)
static int BaseBlock::getOutputNCols (int port)
static void BaseBlock::setOutputPortDimensions (int port, int nrows, int ncols)
Detailed Description
Function Documentation
getOutputArray()
static Array BaseBlock::getOutputArray (int port) inline static
Returns the output port Array.
Definition at line 413 of file baseblock.h.
References BaseBlock::simStruct, and toString().
Referenced by Block::outputs().
getOutputNCols()
static int BaseBlock::getOutputNCols (int port) inline static
Returns the output port number of cols.
Definition at line 439 of file baseblock.h.
References BaseBlock::simStruct.
getOutputNRows()
static int BaseBlock::getOutputNRows (int port) inline static
Returns the output port number of rows.
Definition at line 431 of file baseblock.h.
References BaseBlock::simStruct.
getOutputWidth()
static int BaseBlock::getOutputWidth (int port) inline static
Returns the output port number of elements. If the output port is a 1-D array with w elements, this function returns w. If the output port is an M-by-N array, this function returns m*n.
Definition at line 423 of file baseblock.h.
References BaseBlock::simStruct.
setOutputArray()
static void BaseBlock::setOutputArray (int port, Array & array) inline static
Writes an Array to an output port. Dimensions must agree.
Definition at line 399 of file baseblock.h.
References Array::getData(), Array::getName(), Array::getNCols(), Array::getNRows(), Array::getWidth(), BaseBlock::simStruct, and toString().
Referenced by Block::outputs().
setOutputDouble()
static void BaseBlock::setOutputDouble (int port, double value) inline static
Writes a double or int value to an output port.
Definition at line 390 of file baseblock.h.
References BaseBlock::simStruct.
Referenced by Block::outputs().
setOutputPortDimensions()
static void BaseBlock::setOutputPortDimensions (int port, int nrows, int ncols) inline static
Sets the output port dimensions. Must be used only in initializeOutputPortSizes
Definition at line 448 of file baseblock.h.
References BaseBlock::simStruct.
Referenced by Block::initializeOutputPortSizes(), and BaseBlock::initializeOutputPortSizes().