SIMULINK_ADC: E:/_github/simulink_sm/simulink_adc/src/work/adc_ctrl.h File Reference
adc_ctrl.h File Reference
#include "brd.h"
#include "extn.h"
#include "ctrlstrm.h"
#include "ctrladc.h"
#include "ctrlsdram.h"
#include "ctrlcmpsc.h"
Macros
#define MAX_PU 8
#define MAX_CHAN 32
Functions
void DisplayError (S32 status, const char *func_name, const BRDCHAR *cmd_str)
S32 AdcSettings (BRD_Handle hADC, int idx, BRDCHAR *srvName, BRDCHAR *iniFileName)
S32 SdramSettings (ULONG mem_mode, BRD_Handle hADC, unsigned long long &bBuf_size)
S32 DaqIntoSdram (BRD_Handle hADC)
S32 DaqIntoSdramDMA (BRD_Handle hADC)
S32 DataFromMem (BRD_Handle hADC, PVOID pBuf, ULONG bBufSize, ULONG DmaOn)
S32 DaqIntoFifo (BRD_Handle hADC, PVOID pSig, ULONG bBufSize, int DspMode)
S32 DaqIntoFifoDMA (BRD_Handle hADC)
S32 AllocDaqBuf (BRD_Handle hADC, PVOID *&pSig, unsigned long long *pbytesBufSize, ULONG bufType, ULONG *pBlkNum)
S32 FreeDaqBuf (BRD_Handle hADC, ULONG blkNum)
S32 StartDaqIntoSdramDMA (BRD_Handle hADC, int idx)
void BreakDaqIntoSdramDMA ()
S32 CheckDaqIntoSdramDMA ()
S32 EndDaqIntoSdramDMA ()
void MapWrFlagSinc (int flg, int isNewParam)
int MapRdFlagSinc ()
Variables
const U16 PLD_CFG_TAG = 0x0500
Macro Definition Documentation
MAX_CHAN
#define MAX_CHAN 32
Definition at line 13 of file adc_ctrl.h.
Referenced by AdcSettings(), and MappingIsviParams().
MAX_PU
#define MAX_PU 8
Definition at line 12 of file adc_ctrl.h.
Function Documentation
AdcSettings()
S32 AdcSettings (BRD_Handle hADC, int idx, BRDCHAR * srvName, BRDCHAR * iniFileName)
Definition at line 130 of file adc_ctrl.cpp.
References CheckClock(), DisplayError(), g_AdcDrqFlag, g_bBufSize, g_DirWriteFile, g_FileBufSize, g_fileMap, g_hPostfixFileMap, g_IoDelay, g_MemDrqFlag, g_nPostTrigSamples, g_pPostfix, g_PretrigMode, g_samplesOfChannel, g_samplRate, MappingIsviParams(), and MAX_CHAN.
Referenced by TF_SourceAdc::PrepareAdc().
AllocDaqBuf()
S32 AllocDaqBuf (BRD_Handle hADC, PVOID *& pSig, unsigned long long * pbytesBufSize, ULONG bufType, ULONG * pBlkNum)
Definition at line 806 of file adc_ctrl.cpp.
References DisplayError(), g_buf_dscr, g_fileMap, g_hBufFileMap, g_hFlgFileMap, and g_pFlags.
BreakDaqIntoSdramDMA()
void BreakDaqIntoSdramDMA ()
CheckDaqIntoSdramDMA()
S32 CheckDaqIntoSdramDMA ()
DaqIntoFifo()
S32 DaqIntoFifo (BRD_Handle hADC, PVOID pSig, ULONG bBufSize, int DspMode)
Definition at line 648 of file adc_ctrl.cpp.
References g_MemAsFifo.
DaqIntoFifoDMA()
S32 DaqIntoFifoDMA (BRD_Handle hADC)
Definition at line 697 of file adc_ctrl.cpp.
References DisplayError(), g_AdcDrqFlag, g_bBufSize, g_MemAsFifo, g_MemDrqFlag, and g_transRate.
DaqIntoSdram()
S32 DaqIntoSdram (BRD_Handle hADC)
DaqIntoSdramDMA()
S32 DaqIntoSdramDMA (BRD_Handle hADC)
DataFromMem()
S32 DataFromMem (BRD_Handle hADC, PVOID pBuf, ULONG bBufSize, ULONG DmaOn)
DisplayError()
void DisplayError (S32 status, const char * func_name, const BRDCHAR * cmd_str)
Definition at line 49 of file adc_ctrl.cpp.
Referenced by AdcSettings(), AllocDaqBuf(), DaqIntoFifoDMA(), FreeDaqBuf(), MultiBlkProcWrDir(), and SimpleProcWrDir().
EndDaqIntoSdramDMA()
S32 EndDaqIntoSdramDMA ()
FreeDaqBuf()
S32 FreeDaqBuf (BRD_Handle hADC, ULONG blkNum)
Definition at line 913 of file adc_ctrl.cpp.
References DisplayError(), g_buf_dscr, g_fileMap, g_hBufFileMap, g_hFlgFileMap, and g_pFlags.
MapRdFlagSinc()
int MapRdFlagSinc ()
Definition at line 1012 of file adc_ctrl.cpp.
References g_pFlags.
MapWrFlagSinc()
void MapWrFlagSinc (int flg, int isNewParam)
Definition at line 1005 of file adc_ctrl.cpp.
References g_buf_dscr, and g_pFlags.
SdramSettings()
S32 SdramSettings (ULONG mem_mode, BRD_Handle hADC, unsigned long long & bBuf_size)
StartDaqIntoSdramDMA()
S32 StartDaqIntoSdramDMA (BRD_Handle hADC, int idx)
Variable Documentation
PLD_CFG_TAG
const U16 PLD_CFG_TAG = 0x0500
Definition at line 15 of file adc_ctrl.h.