SIMULINK_A7DAC: TF_A7DacCtrl Class Reference
TF_A7DacCtrl Class Reference
Source data base class.
#include <TF_A7DacCtrl.h>
Public Member Functions
TF_A7DacCtrl (int argc, BRDCHAR **argv)
virtual ~TF_A7DacCtrl ()
virtual int Prepare (int count)
Prepare function.
virtual void ReStartSession (void)
Start new session of process data.
virtual void EventStartCycle (void)
Start of new data cycle.
void EventStartCycle (int flagChange, double *param)
int isCycleCompletion (void)
Public Member Functions inherited from TF_BaseSource
TF_BaseSource (int argc, BRDCHAR **argv)
virtual ~TF_BaseSource ()
virtual int GetData (U32 **ptr)
Get buffer of data.
Private Attributes
TF_A7DacCtrl_TaskData * td
Internal data of TF_A7DacCtrl.
Detailed Description
Source data base class.
Definition at line 12 of file TF_A7DacCtrl.h.
Constructor & Destructor Documentation
TF_A7DacCtrl()
TF_A7DacCtrl::TF_A7DacCtrl (int argc, BRDCHAR ** argv)
Definition at line 45 of file TF_A7DacCtrl.cpp.
References td.
~TF_A7DacCtrl()
TF_A7DacCtrl::~TF_A7DacCtrl () virtual
Definition at line 51 of file TF_A7DacCtrl.cpp.
References td.
Member Function Documentation
EventStartCycle() [1/2]
void TF_A7DacCtrl::EventStartCycle (void) virtual
Start of new data cycle.
Reimplemented from TF_BaseSource.
Definition at line 161 of file TF_A7DacCtrl.cpp.
Referenced by TF_SimulinkA7Dac::Execute().
EventStartCycle() [2/2]
void TF_A7DacCtrl::EventStartCycle (int flagChange, double * param)
Definition at line 165 of file TF_A7DacCtrl.cpp.
References TF_DDS::DacStart(), TF_A7DacCtrl_TaskData::dds, TF_A7DacCtrl_TaskData::flagStart, TF_PLL::GetFreq(), TF_A7DacCtrl_TaskData::pll, TF_DDS::SetCntStart(), TF_DDS::SetDacFreq(), and td.
isCycleCompletion()
int TF_A7DacCtrl::isCycleCompletion (void)
Definition at line 178 of file TF_A7DacCtrl.cpp.
References TF_DDS::DacStart(), TF_A7DacCtrl_TaskData::dds, TF_DDS::isPeriodComplete(), and td.
Referenced by TF_SimulinkA7Dac::Execute().
Prepare()
int TF_A7DacCtrl::Prepare (int count) virtual
Prepare function.
Reimplemented from TF_BaseSource.
Definition at line 57 of file TF_A7DacCtrl.cpp.
References TF_A7DacCtrl_TaskData::a7dac, TF_A7DacCtrl_TaskData::dds, TF_PLL::GetFreq(), TF_A7Dac::Open(), TF_A7Dac::PkgCmdExecute(), TF_A7Dac::PkgCmdRead(), TF_A7Dac::PkgCmdStart(), TF_A7Dac::PkgCmdWrite(), TF_A7DacCtrl_TaskData::pll, TF_PLL::Prepare(), TF_DDS::Prepare(), TF_DDS::SetCntStart(), TF_DDS::SetDacFreq(), TF_PLL::SetDiv(), TF_PLL::SetPll(), and td.
Referenced by TF_SimulinkA7Dac::Prepare().
ReStartSession()
void TF_A7DacCtrl::ReStartSession (void) virtual
Start new session of process data.
Reimplemented from TF_BaseSource.
Definition at line 153 of file TF_A7DacCtrl.cpp.
References TF_DDS::DacStart(), TF_A7DacCtrl_TaskData::dds, TF_A7DacCtrl_TaskData::flagStart, and td.
Referenced by TF_SimulinkA7Dac::Execute().
Member Data Documentation
td
TF_A7DacCtrl_TaskData* TF_A7DacCtrl::td private
Internal data of TF_A7DacCtrl.
Definition at line 16 of file TF_A7DacCtrl.h.
Referenced by EventStartCycle(), isCycleCompletion(), Prepare(), ReStartSession(), TF_A7DacCtrl(), and ~TF_A7DacCtrl().
The documentation for this class was generated from the following files:
E:/_github/simulink_sm/simulink_a7dac/src/work/TF_A7DacCtrl.h
E:/_github/simulink_sm/simulink_a7dac/src/work/TF_A7DacCtrl.cpp