SM_ADC: Block Class Reference
Block Class Reference
S-Function sm_adc.mex64w.
#include <sm_adc.h>
Public Member Functions
void start ()
void outputs ()
void terminate ()
Public Member Functions inherited from BaseBlock
void start ()
void outputs ()
void derivatives ()
void zeroCrossings ()
void update ()
void terminate ()
Private Attributes
int flagLowVal_0
int flagLowVal_1
int flagHighVal_0
int flagHighVal_1
int flagError
unsigned indexReq
unsigned indexWr
int m_DataSize
string m_SharedFileName
TF_SimulinkShared * m_pSimulinkShared
Additional Inherited Members
Static Public Member Functions inherited from BaseBlock
static void setSimStruct (SimStruct *S)
static void initializeParameterPortSizes ()
static void initializeInputPortSizes ()
static void initializeOutputPortSizes ()
static void initializeStatePortSizes ()
static void initializeNumberSampleTimes ()
static void initializeOptions ()
static void setInputPortDimensionInfo (int port, const DimsInfo_T *dimsInfo)
static void setOutputPortDimensionInfo (int port, const DimsInfo_T *dimsInfo)
static void checkParameters ()
static void initializeSampleTimes ()
static double getInputDouble (int port)
static double getInputInt (int port)
static Array getInputArray (int port)
static int getInputWidth (int port)
static int getInputNRows (int port)
static int getInputNCols (int port)
static void setInputPortDimensions (int port, int nrows, int ncols)
static void setOutputDouble (int port, double value)
static void setOutputArray (int port, Array &array)
static Array getOutputArray (int port)
static int getOutputWidth (int port)
static int getOutputNRows (int port)
static int getOutputNCols (int port)
static void setOutputPortDimensions (int port, int nrows, int ncols)
static double getParameterDouble (int port)
static int getParameterInt (int port)
static string getParameterString (int port)
static Array getParameterArray (int port)
static int getParameterWidth (int port)
static int getParameterNRows (int port)
static int getParameterNCols (int port)
static Array getContinuousStateArray ()
static int getContinuousStateWidth (int port)
static void setDerivativeStateArray (Array &array)
static Array getDiscreteStateArray ()
static int getDiscreteStateWidth (int port)
static void setDiscreteStateArray (Array &array)
static void setContinuousStatesNumber (int num)
static void setDiscreteStatesNumber (int num)
static time_T getCurrentTime ()
Static Protected Attributes inherited from BaseBlock
static SimStruct * simStruct =NULL
Detailed Description
S-Function sm_adc.mex64w.
Definition at line 104 of file sm_adc.h.
Member Function Documentation
outputs()
void Block::outputs ()
Definition at line 92 of file sm_adc.cpp.
References DATA, flagError, flagHighVal_0, flagLowVal_0, flagLowVal_1, GET_DATA, TF_SimulinkShared::GetBuf(), TF_SimulinkShared::GetFlag(), BaseBlock::getInputDouble(), indexReq, indexWr, BaseBlock::initializeSampleTimes(), m_DataSize, m_pSimulinkShared, TF_SimulinkShared::SetFlag(), BaseBlock::setOutputArray(), BaseBlock::setOutputDouble(), start(), START_IN, and START_OUT.
Referenced by mdlOutputs().
start()
void Block::start ()
Definition at line 14 of file sm_adc.cpp.
References blockSize, DATA_SIZE, flagError, flagLowVal_0, flagLowVal_1, FNAME, TF_SimulinkShared::GetFlag(), BaseBlock::getParameterInt(), BaseBlock::getParameterString(), indexReq, indexWr, m_DataSize, m_pSimulinkShared, m_SharedFileName, and TF_SimulinkShared::SetFlag().
Referenced by mdlStart(), and outputs().
terminate()
void Block::terminate ()
Definition at line 260 of file sm_adc.cpp.
Referenced by mdlTerminate().
Member Data Documentation
flagError
int Block::flagError private
Definition at line 116 of file sm_adc.h.
Referenced by outputs(), and start().
flagHighVal_0
int Block::flagHighVal_0 private
Definition at line 113 of file sm_adc.h.
Referenced by outputs().
flagHighVal_1
int Block::flagHighVal_1 private
Definition at line 114 of file sm_adc.h.
flagLowVal_0
int Block::flagLowVal_0 private
Definition at line 110 of file sm_adc.h.
Referenced by outputs(), and start().
flagLowVal_1
int Block::flagLowVal_1 private
Definition at line 111 of file sm_adc.h.
Referenced by outputs(), and start().
indexReq
unsigned Block::indexReq private
Definition at line 118 of file sm_adc.h.
Referenced by outputs(), and start().
indexWr
unsigned Block::indexWr private
Definition at line 119 of file sm_adc.h.
Referenced by outputs(), and start().
m_DataSize
int Block::m_DataSize private
Definition at line 121 of file sm_adc.h.
Referenced by outputs(), and start().
m_pSimulinkShared
TF_SimulinkShared* Block::m_pSimulinkShared private
Definition at line 124 of file sm_adc.h.
Referenced by outputs(), and start().
m_SharedFileName
string Block::m_SharedFileName private
Definition at line 122 of file sm_adc.h.
Referenced by start().
The documentation for this class was generated from the following files:
E:/_github/simulink_sm/simulink_sm/src/mex/sm_adc.h
E:/_github/simulink_sm/simulink_sm/src/mex/sm_adc.cpp