SIMULINK_ADC: TF_BaseSource Class Reference
TF_BaseSource Class Reference
Source data base class.
#include <TF_BaseSource.h>
Public Member Functions
TF_BaseSource (int argc, BRDCHAR **argv)
virtual ~TF_BaseSource ()
virtual int Prepare (int count)
Prepare function.
virtual void ReStartSession (void)
Start new session of process data.
virtual void EventStartCycle (void)
Start of new data cycle.
virtual int GetData (U32 **ptr)
Get buffer of data.
Detailed Description
Source data base class.
Definition at line 11 of file TF_BaseSource.h.
Constructor & Destructor Documentation
TF_BaseSource()
TF_BaseSource::TF_BaseSource (int argc, BRDCHAR ** argv) inline
Definition at line 16 of file TF_BaseSource.h.
~TF_BaseSource()
virtual TF_BaseSource::~TF_BaseSource () inline virtual
Definition at line 17 of file TF_BaseSource.h.
Member Function Documentation
EventStartCycle()
virtual void TF_BaseSource::EventStartCycle (void) inline virtual
Start of new data cycle.
Reimplemented in TF_SourceAdc, and TF_SourceImit.
Definition at line 26 of file TF_BaseSource.h.
Referenced by TF_SimulinkAdc::Execute().
GetData()
virtual int TF_BaseSource::GetData (U32 ** ptr) inline virtual
Get buffer of data.
Parameters
ptr pointer of pointer of data, output
Returns
1 - set new pointer to ptr
Reimplemented in TF_SourceAdc, and TF_SourceImit.
Definition at line 33 of file TF_BaseSource.h.
Referenced by TF_SimulinkAdc::Execute().
Prepare()
virtual int TF_BaseSource::Prepare (int count) inline virtual
Prepare function.
Reimplemented in TF_SourceAdc, and TF_SourceImit.
Definition at line 20 of file TF_BaseSource.h.
Referenced by TF_SimulinkAdc::Prepare().
ReStartSession()
virtual void TF_BaseSource::ReStartSession (void) inline virtual
Start new session of process data.
Reimplemented in TF_SourceAdc, and TF_SourceImit.
Definition at line 23 of file TF_BaseSource.h.
Referenced by TF_SimulinkAdc::Execute().
The documentation for this class was generated from the following file:
E:/_github/simulink_sm/simulink_adc/src/work/TF_BaseSource.h