SM_ADC: E:/_github/simulink_sm/simulink_sm/src/easyLink-3.3.0/include/mdldefinitions.h File Reference
mdldefinitions.h File Reference
#include "cg_sfun.h"
Macros
#define MDL_CHECK_PARAMETERS
#define MDL_INITIALIZE_SIZES
#define MDL_SET_INPUT_PORT_DIMENSION_INFO
#define MDL_SET_OUTPUT_PORT_DIMENSION_INFO
#define MDL_INITIALIZE_SAMPLE_TIME
#define MDL_START
#define MDL_OUTPUTS
#define MDL_DERIVATIVES
#define MDL_ZERO_CROSSINGS
#define MDL_UPDATE
#define MDL_TERMINATE
Functions
static void mdlCheckParameters (SimStruct *S)
static void mdlInitializeSizes (SimStruct *S)
static void mdlSetInputPortDimensionInfo (SimStruct *S, int port, const DimsInfo_T *dimsInfo)
static void mdlSetOutputPortDimensionInfo (SimStruct *S, int port, const DimsInfo_T *dimsInfo)
static void mdlInitializeSampleTimes (SimStruct *S)
static void mdlStart (SimStruct *S)
static void mdlOutputs (SimStruct *S, int tid)
static void mdlDerivatives (SimStruct *S)
static void mdlZeroCrossings (SimStruct *S)
static void mdlUpdate (SimStruct *S, int tid)
static void mdlTerminate (SimStruct *S)
Macro Definition Documentation
MDL_CHECK_PARAMETERS
#define MDL_CHECK_PARAMETERS
Definition at line 13 of file mdldefinitions.h.
MDL_DERIVATIVES
#define MDL_DERIVATIVES
Definition at line 166 of file mdldefinitions.h.
MDL_INITIALIZE_SAMPLE_TIME
#define MDL_INITIALIZE_SAMPLE_TIME
Definition at line 103 of file mdldefinitions.h.
MDL_INITIALIZE_SIZES
#define MDL_INITIALIZE_SIZES
Definition at line 33 of file mdldefinitions.h.
MDL_OUTPUTS
#define MDL_OUTPUTS
Definition at line 145 of file mdldefinitions.h.
MDL_SET_INPUT_PORT_DIMENSION_INFO
#define MDL_SET_INPUT_PORT_DIMENSION_INFO
Definition at line 62 of file mdldefinitions.h.
MDL_SET_OUTPUT_PORT_DIMENSION_INFO
#define MDL_SET_OUTPUT_PORT_DIMENSION_INFO
Definition at line 83 of file mdldefinitions.h.
MDL_START
#define MDL_START
Definition at line 123 of file mdldefinitions.h.
MDL_TERMINATE
#define MDL_TERMINATE
Definition at line 229 of file mdldefinitions.h.
MDL_UPDATE
#define MDL_UPDATE
Definition at line 208 of file mdldefinitions.h.
MDL_ZERO_CROSSINGS
#define MDL_ZERO_CROSSINGS
Definition at line 187 of file mdldefinitions.h.
Function Documentation
mdlCheckParameters()
static void mdlCheckParameters (SimStruct * S) static
Definition at line 14 of file mdldefinitions.h.
References BaseBlock::checkParameters(), ERROR_MSG_BUFFER, and BaseBlock::setSimStruct().
Referenced by mdlInitializeSizes().
mdlDerivatives()
static void mdlDerivatives (SimStruct * S) static
Definition at line 167 of file mdldefinitions.h.
References BaseBlock::derivatives(), ERROR_MSG_BUFFER, and BaseBlock::setSimStruct().
mdlInitializeSampleTimes()
static void mdlInitializeSampleTimes (SimStruct * S) static
Definition at line 104 of file mdldefinitions.h.
References ERROR_MSG_BUFFER, BaseBlock::initializeSampleTimes(), and BaseBlock::setSimStruct().
mdlInitializeSizes()
static void mdlInitializeSizes (SimStruct * S) static
Definition at line 34 of file mdldefinitions.h.
References ERROR_MSG_BUFFER, BaseBlock::initializeInputPortSizes(), BaseBlock::initializeNumberSampleTimes(), BaseBlock::initializeOptions(), BaseBlock::initializeOutputPortSizes(), BaseBlock::initializeParameterPortSizes(), BaseBlock::initializeStatePortSizes(), mdlCheckParameters(), and BaseBlock::setSimStruct().
mdlOutputs()
static void mdlOutputs (SimStruct * S, int tid) static
Definition at line 146 of file mdldefinitions.h.
References ERROR_MSG_BUFFER, BaseBlock::getCurrentTime(), Block::outputs(), and BaseBlock::setSimStruct().
mdlSetInputPortDimensionInfo()
static void mdlSetInputPortDimensionInfo (SimStruct * S, int port, const DimsInfo_T * dimsInfo) static
Definition at line 63 of file mdldefinitions.h.
References ERROR_MSG_BUFFER, BaseBlock::setInputPortDimensionInfo(), and BaseBlock::setSimStruct().
mdlSetOutputPortDimensionInfo()
static void mdlSetOutputPortDimensionInfo (SimStruct * S, int port, const DimsInfo_T * dimsInfo) static
Definition at line 84 of file mdldefinitions.h.
References ERROR_MSG_BUFFER, BaseBlock::setOutputPortDimensionInfo(), and BaseBlock::setSimStruct().
mdlStart()
static void mdlStart (SimStruct * S) static
Definition at line 124 of file mdldefinitions.h.
References ERROR_MSG_BUFFER, BaseBlock::setSimStruct(), and Block::start().
mdlTerminate()
static void mdlTerminate (SimStruct * S) static
Definition at line 230 of file mdldefinitions.h.
References ERROR_MSG_BUFFER, BaseBlock::setSimStruct(), and Block::terminate().
mdlUpdate()
static void mdlUpdate (SimStruct * S, int tid) static
Definition at line 209 of file mdldefinitions.h.
References ERROR_MSG_BUFFER, BaseBlock::setSimStruct(), and BaseBlock::update().
mdlZeroCrossings()
static void mdlZeroCrossings (SimStruct * S) static
Definition at line 188 of file mdldefinitions.h.
References ERROR_MSG_BUFFER, BaseBlock::setSimStruct(), and BaseBlock::zeroCrossings().