SIMULINK_A7DAC: TF_Test Class Reference
TF_Test Class Reference abstract
#include <TF_Test.h>
Public Member Functions
virtual ~TF_Test ()
virtual void Prepare (void)=0
virtual void Start (void)=0
virtual void Stop (void)=0
virtual int isComplete (void)=0
virtual void GetResult (void)=0
virtual void Step (void)=0
Detailed Description
Definition at line 5 of file TF_Test.h.
Constructor & Destructor Documentation
~TF_Test()
virtual TF_Test::~TF_Test () inline virtual
Definition at line 11 of file TF_Test.h.
Member Function Documentation
GetResult()
virtual void TF_Test::GetResult (void) pure virtual
Implemented in TF_SimulinkA7Dac.
Referenced by BRDC_main().
isComplete()
virtual int TF_Test::isComplete (void) pure virtual
Implemented in TF_SimulinkA7Dac.
Referenced by BRDC_main().
Prepare()
virtual void TF_Test::Prepare (void) pure virtual
Implemented in TF_SimulinkA7Dac.
Referenced by BRDC_main().
Start()
virtual void TF_Test::Start (void) pure virtual
Implemented in TF_SimulinkA7Dac.
Referenced by BRDC_main().
Step()
virtual void TF_Test::Step (void) pure virtual
Implemented in TF_SimulinkA7Dac.
Referenced by BRDC_main().
Stop()
virtual void TF_Test::Stop (void) pure virtual
Implemented in TF_SimulinkA7Dac.
Referenced by BRDC_main().
The documentation for this class was generated from the following file:
E:/_github/simulink_sm/simulink_a7dac/src/work/TF_Test.h