SM_ADC: S-function parameters managing methods
S-function parameters managing methods
Functions
static double BaseBlock::getParameterDouble (int port)
static int BaseBlock::getParameterInt (int port)
static string BaseBlock::getParameterString (int port)
static Array BaseBlock::getParameterArray (int port)
static int BaseBlock::getParameterWidth (int port)
static int BaseBlock::getParameterNRows (int port)
static int BaseBlock::getParameterNCols (int port)
Detailed Description
Function Documentation
getParameterArray()
static Array BaseBlock::getParameterArray (int port) inline static
Returns an Array connected to a parameter port.
Definition at line 486 of file baseblock.h.
References BaseBlock::simStruct, and toString().
Referenced by Block::outputs(), and Block::start().
getParameterDouble()
static double BaseBlock::getParameterDouble (int port) inline static
Returns the double value of a parameter port.
Definition at line 460 of file baseblock.h.
References BaseBlock::simStruct.
Referenced by Block::outputs().
getParameterInt()
static int BaseBlock::getParameterInt (int port) inline static
Returns the int value of a parameter port.
Definition at line 468 of file baseblock.h.
References BaseBlock::simStruct.
Referenced by Block::initializeOutputPortSizes(), and Block::outputs().
getParameterNCols()
static int BaseBlock::getParameterNCols (int port) inline static
Returns the parameter port number of cols.
Definition at line 513 of file baseblock.h.
References BaseBlock::simStruct.
getParameterNRows()
static int BaseBlock::getParameterNRows (int port) inline static
Returns the parameter port number of rows.
Definition at line 505 of file baseblock.h.
References BaseBlock::simStruct.
Referenced by Block::initializeOutputPortSizes(), Block::initializeStatePortSizes(), and Block::outputs().
getParameterString()
static string BaseBlock::getParameterString (int port) inline static
Returns the string value of a parameter port.
Definition at line 476 of file baseblock.h.
References BaseBlock::simStruct.
Referenced by BaseBlock::checkParameters(), and Block::outputs().
getParameterWidth()
static int BaseBlock::getParameterWidth (int port) inline static
Returns the parameter port number of elements.
If the parameter port is a 1-D array with w elements, this function returns w. If the parameter port is an M-by-N array, this function returns m*n.
Definition at line 497 of file baseblock.h.
References BaseBlock::simStruct.