SIMULINK_ADC: CL_AMBPEX Class Reference
CL_AMBPEX Class Reference
Работа с аппаратным модулем через библиотеку BARDY.
#include <CL_AMBPEX.h>
Classes
struct StreamParam
Public Member Functions
virtual U32 init (U32 lid)
Инициализация модуля
virtual void cleanup (void)
Завершение работы с модулем
int StreamInit (U32 strm, U32 cnt_buf, U32 size_one_buf_of_bytes, U32 trd, U32 dir, U32 cycle, U32 system, U32 agree_mode)
int StreamInit_Mode8 (void **ppBlk, U32 strm, U32 cnt_buf, U32 size_one_buf_of_bytes, U32 trd, U32 dir, U32 cycle, U32 agree_mode)
Выделение памяти для стрима в режиме 8.
void StreamDestroy (U32 strm)
void StreamDestroyEx (U32 strm)
U32 * StreamGetBufByNum (U32 strm, U32 numBuf)
void StreamStart (U32 strm)
void StreamStartEx (U32 strm)
int StreamSetTrd (U32 strm, U32 trd)
void StreamStop (U32 strm)
void StreamStopEx (U32 strm)
int StreamGetBuf (U32 strm, U32 **ptr)
int StreamGetIndexDma (U32 strm)
int StreamGetNextIndex (U32 strm, U32 index)
void StreamGetBufDone (U32 strm)
BRD_Handle StreamGetHandle (U32 strm)
Доступ к дескриптору стрима
U32 * StreamGetStub (U32 strm)
Доступ к адресу блочка
void RegPokeInd (S32 trdNo, S32 rgnum, U32 val)
Запись в косвенно адресуемый регистр
U32 RegPeekInd (S32 trdNo, S32 rgnum)
Чтение из косвенно адресуемого регистра
void RegPokeDir (S32 trdNo, S32 rgnum, U32 val)
Запись в прямой регистр
U32 RegPeekDir (S32 trdNo, S32 rgnum)
Чтение из прямого регистра
void GetPhysAdr (U64 &blkAdr, U64 &trdAdr)
Получение физических адресов BAR0, BAR1.
CL_AMBPEX ()
~CL_AMBPEX ()
BRD_Handle GetSrvHandle (BRDCHAR *name, U32 *atr, U32 mode=BRDcapt_EXCLUSIVE)
Запрос дескриптора службы
BRD_Handle GetHandle (void)
Запрос дескрипотора модуля
BRD_Handle GetHandleReg (void)
Запрос дескрипотора службы REG0.
void ShowServiceList (void)
Вывод списка служб
void ShowBrdInfo (void)
Вывод информации о модуле
void PkgCmdStart (void)
Начало формирования пакета команды
void PkgCmdPokeInd (U32 trd, U32 reg, U32 val)
Добавление команды записи в косвенный регистр
void PkgCmdPokeDir (U32 trd, U32 reg, U32 val)
Добавлние команды записи в прямой регистр
void PkgCmdPeekInd (U32 trd, U32 reg, U32 *val)
Добавление команды чтения из косвенного регистра
void PkgCmdPeekDir (U32 trd, U32 reg, U32 *val)
Добавление команды чтение из прямого регистра
void PkgCmdExecute (void)
Выполние команды
Public Attributes
BRD_Info info
Информация о модуле
Private Attributes
BRD_Handle m_hBrd
U32 m_nLid
Логический идентификатор модуля
U64 m_blkPhysAdr
Физический адрес окна памяти 0 в ПЛИС - блоки управления
U64 m_trdPhysAdr
Физический адрес окна памяти 1 в ПЛИС - тетрады
cl_ambpex_task_data * td
внутренние данные класса
BRD_Handle m_hReg
Дескриптор служды для обращения к регистрам
StreamParam m_streamParam [4]
Static Private Attributes
static int m_isInit =0
1 - выполнена функция BRD_Init
Detailed Description
Работа с аппаратным модулем через библиотеку BARDY.
Описание библиотеки приведено в документе "DCR0328 - Управляющая библиотека BARDY".
Обращение к регистрам производится через службу REG0, в файле brd.ini требуется подключение devreg.
Класс обеспечивает инициализацию модуля, обращения к регистрам тетрады, работу со стримами.
Definition at line 23 of file CL_AMBPEX.h.
Constructor & Destructor Documentation
CL_AMBPEX()
CL_AMBPEX::CL_AMBPEX ()
Definition at line 129 of file CL_AMBPEX.cpp.
References m_hBrd, and td.
~CL_AMBPEX()
CL_AMBPEX::~CL_AMBPEX ()
Definition at line 136 of file CL_AMBPEX.cpp.
References m_hBrd, and td.
Member Function Documentation
cleanup()
void CL_AMBPEX::cleanup (void) virtual
Завершение работы с модулем
Definition at line 115 of file CL_AMBPEX.cpp.
GetHandle()
BRD_Handle CL_AMBPEX::GetHandle (void)
Запрос дескрипотора модуля
Definition at line 876 of file CL_AMBPEX.cpp.
References m_hBrd.
GetHandleReg()
BRD_Handle CL_AMBPEX::GetHandleReg (void)
Запрос дескрипотора службы REG0.
Definition at line 882 of file CL_AMBPEX.cpp.
References m_hReg.
GetPhysAdr()
void CL_AMBPEX::GetPhysAdr (U64 & blkAdr, U64 & trdAdr)
Получение физических адресов BAR0, BAR1.
Definition at line 1094 of file CL_AMBPEX.cpp.
References m_blkPhysAdr, and m_trdPhysAdr.
GetSrvHandle()
BRD_Handle CL_AMBPEX::GetSrvHandle (BRDCHAR * name, U32 * atr, U32 mode = BRDcapt_EXCLUSIVE)
Запрос дескриптора службы
Parameters
name имя службы
atr атрибуты службы
Returns
дескриптор службы
Службы модуля
Число служб
Definition at line 155 of file CL_AMBPEX.cpp.
References m_hBrd.
Referenced by init(), TF_SourceAdc::PrepareAdc(), StreamInit(), and StreamInit_Mode8().
init()
U32 CL_AMBPEX::init (U32 lid) virtual
Инициализация модуля
Definition at line 34 of file CL_AMBPEX.cpp.
References GetSrvHandle(), info, m_blkPhysAdr, m_hBrd, m_hReg, m_isInit, m_nLid, m_trdPhysAdr, and RegPokeInd().
Referenced by TF_SourceAdc::Prepare().
PkgCmdExecute()
void CL_AMBPEX::PkgCmdExecute (void)
Выполние команды
Definition at line 1188 of file CL_AMBPEX.cpp.
References cl_ambpex_task_data::count, cl_ambpex_task_data::data, except_info(), m_hReg, cl_ambpex_task_data::reg, cl_ambpex_task_data::status, and td.
PkgCmdPeekDir()
void CL_AMBPEX::PkgCmdPeekDir (U32 trd, U32 reg, U32 * val)
Добавление команды чтение из прямого регистра
Definition at line 1169 of file CL_AMBPEX.cpp.
References cl_ambpex_task_data::count, cl_ambpex_task_data::data, except_info(), cl_ambpex_task_data::reg, cl_ambpex_task_data::status, and td.
PkgCmdPeekInd()
void CL_AMBPEX::PkgCmdPeekInd (U32 trd, U32 reg, U32 * val)
Добавление команды чтения из косвенного регистра
Definition at line 1149 of file CL_AMBPEX.cpp.
References cl_ambpex_task_data::count, cl_ambpex_task_data::data, except_info(), cl_ambpex_task_data::reg, cl_ambpex_task_data::status, and td.
PkgCmdPokeDir()
void CL_AMBPEX::PkgCmdPokeDir (U32 trd, U32 reg, U32 val)
Добавлние команды записи в прямой регистр
Definition at line 1129 of file CL_AMBPEX.cpp.
References cl_ambpex_task_data::count, cl_ambpex_task_data::data, except_info(), cl_ambpex_task_data::reg, cl_ambpex_task_data::status, and td.
PkgCmdPokeInd()
void CL_AMBPEX::PkgCmdPokeInd (U32 trd, U32 reg, U32 val)
Добавление команды записи в косвенный регистр
Definition at line 1110 of file CL_AMBPEX.cpp.
References cl_ambpex_task_data::count, cl_ambpex_task_data::data, except_info(), cl_ambpex_task_data::reg, cl_ambpex_task_data::status, and td.
PkgCmdStart()
void CL_AMBPEX::PkgCmdStart (void)
Начало формирования пакета команды
Definition at line 1103 of file CL_AMBPEX.cpp.
References cl_ambpex_task_data::count, cl_ambpex_task_data::status, and td.
RegPeekDir()
U32 CL_AMBPEX::RegPeekDir (S32 trdNo, S32 rgnum)
Чтение из прямого регистра
Definition at line 302 of file CL_AMBPEX.cpp.
References m_hReg.
Referenced by ShowBrdInfo().
RegPeekInd()
U32 CL_AMBPEX::RegPeekInd (S32 trdNo, S32 rgnum)
Чтение из косвенно адресуемого регистра
Definition at line 268 of file CL_AMBPEX.cpp.
References m_hReg.
Referenced by ShowBrdInfo(), and StreamStart().
RegPokeDir()
void CL_AMBPEX::RegPokeDir (S32 trdNo, S32 rgnum, U32 val)
Запись в прямой регистр
Definition at line 287 of file CL_AMBPEX.cpp.
References m_hReg.
Referenced by ShowBrdInfo().
RegPokeInd()
void CL_AMBPEX::RegPokeInd (S32 trdNo, S32 rgnum, U32 val)
Запись в косвенно адресуемый регистр
Definition at line 253 of file CL_AMBPEX.cpp.
References m_hReg.
Referenced by TF_SourceAdc::EventStartCycle(), init(), and StreamStop().
ShowBrdInfo()
void CL_AMBPEX::ShowBrdInfo (void)
Вывод информации о модуле
Definition at line 915 of file CL_AMBPEX.cpp.
References m_nLid, RegPeekDir(), RegPeekInd(), and RegPokeDir().
ShowServiceList()
void CL_AMBPEX::ShowServiceList (void)
Вывод списка служб
Parameters
name имя службы
atr атрибуты службы
Returns
дескриптор службы
Службы модуля
Число служб
Definition at line 220 of file CL_AMBPEX.cpp.
References m_hBrd.
StreamDestroy()
void CL_AMBPEX::StreamDestroy (U32 strm)
Definition at line 628 of file CL_AMBPEX.cpp.
References CL_AMBPEX::StreamParam::hStream, m_streamParam, CL_AMBPEX::StreamParam::status, and StreamStop().
Referenced by StreamInit(), StreamInit_Mode8(), and TF_SourceAdc::~TF_SourceAdc().
StreamDestroyEx()
void CL_AMBPEX::StreamDestroyEx (U32 strm)
Освобождение памяти и службы стрима без остановки тетрады
Definition at line 891 of file CL_AMBPEX.cpp.
References CL_AMBPEX::StreamParam::hStream, m_streamParam, and CL_AMBPEX::StreamParam::status.
StreamGetBuf()
int CL_AMBPEX::StreamGetBuf (U32 strm, U32 ** ptr)
Definition at line 789 of file CL_AMBPEX.cpp.
References CL_AMBPEX::StreamParam::indexDma, CL_AMBPEX::StreamParam::indexPc, m_streamParam, CL_AMBPEX::StreamParam::statusStart, StreamGetBufByNum(), StreamGetIndexDma(), and StreamGetNextIndex().
Referenced by TF_SourceAdc::GetData().
StreamGetBufByNum()
U32 * CL_AMBPEX::StreamGetBufByNum (U32 strm, U32 numBuf)
Definition at line 651 of file CL_AMBPEX.cpp.
References CL_AMBPEX::StreamParam::cnt_buf, m_streamParam, CL_AMBPEX::StreamParam::pBlk, and CL_AMBPEX::StreamParam::status.
Referenced by StreamGetBuf().
StreamGetBufDone()
void CL_AMBPEX::StreamGetBufDone (U32 strm)
Definition at line 855 of file CL_AMBPEX.cpp.
References CL_AMBPEX::StreamParam::agree_mode, CL_AMBPEX::StreamParam::hStream, CL_AMBPEX::StreamParam::indexPc, and m_streamParam.
StreamGetHandle()
BRD_Handle CL_AMBPEX::StreamGetHandle (U32 strm)
Доступ к дескриптору стрима
Definition at line 1071 of file CL_AMBPEX.cpp.
References CL_AMBPEX::StreamParam::hStream, and m_streamParam.
StreamGetIndexDma()
int CL_AMBPEX::StreamGetIndexDma (U32 strm)
Definition at line 818 of file CL_AMBPEX.cpp.
References m_streamParam, and CL_AMBPEX::StreamParam::pStub.
Referenced by StreamGetBuf().
StreamGetNextIndex()
int CL_AMBPEX::StreamGetNextIndex (U32 strm, U32 index)
Definition at line 615 of file CL_AMBPEX.cpp.
References CL_AMBPEX::StreamParam::cnt_buf, and m_streamParam.
Referenced by StreamGetBuf().
StreamGetStub()
U32 * CL_AMBPEX::StreamGetStub (U32 strm)
Доступ к адресу блочка
Definition at line 1081 of file CL_AMBPEX.cpp.
References m_streamParam, and CL_AMBPEX::StreamParam::pStub.
StreamInit()
int CL_AMBPEX::StreamInit (U32 strm, U32 cnt_buf, U32 size_one_buf_of_bytes, U32 trd, U32 dir, U32 cycle, U32 system, U32 agree_mode)
Выделение памяти для службы
< Направление работы стрима, 1 - в ПЭВМ, 2 - из ПЭВМ
< Как создавать составной буфера, 0 - разрывный
< Количество блоков в составном буфере
< Размер одного блока
< Массив адресов блоков
< Указатель на блочек
Вызов с реальным количеством блоков
Definition at line 322 of file CL_AMBPEX.cpp.
References CL_AMBPEX::StreamParam::agree_mode, CL_AMBPEX::StreamParam::cnt_buf, CL_AMBPEX::StreamParam::cycle, GetSrvHandle(), CL_AMBPEX::StreamParam::hStream, CL_AMBPEX::StreamParam::indexDma, CL_AMBPEX::StreamParam::indexPc, m_streamParam, CL_AMBPEX::StreamParam::pBlk, CL_AMBPEX::StreamParam::pStub, CL_AMBPEX::StreamParam::size_one_buf_of_bytes, CL_AMBPEX::StreamParam::status, StreamDestroy(), CL_AMBPEX::StreamParam::system, and CL_AMBPEX::StreamParam::trd.
Referenced by TF_SourceAdc::Prepare().
StreamInit_Mode8()
int CL_AMBPEX::StreamInit_Mode8 (void ** ppBlk, U32 strm, U32 cnt_buf, U32 size_one_buf_of_bytes, U32 trd, U32 dir, U32 cycle, U32 agree_mode)
Выделение памяти для стрима в режиме 8.
В режиме 8 массив ppBlk содержит физические адреса блоков памяти. Бит 0 адреса используется для факта создания прерывания. Наличие 1 означает что прерывание будет сформировано.
Выделение памяти для службы
< Направление работы стрима, 1 - в ПЭВМ, 2 - из ПЭВМ
< Как создавать составной буфера, 8 - создание из таблицы физических адресов с маской прерывания
< Количество блоков в составном буфере
< Размер одного блока
< Массив адресов блоков
< Указатель на блочек
Вызов с реальным количеством блоков
Definition at line 468 of file CL_AMBPEX.cpp.
References CL_AMBPEX::StreamParam::agree_mode, CL_AMBPEX::StreamParam::cnt_buf, CL_AMBPEX::StreamParam::cycle, GetSrvHandle(), CL_AMBPEX::StreamParam::hStream, CL_AMBPEX::StreamParam::indexDma, CL_AMBPEX::StreamParam::indexPc, m_streamParam, CL_AMBPEX::StreamParam::pBlk, CL_AMBPEX::StreamParam::pStub, CL_AMBPEX::StreamParam::size_one_buf_of_bytes, CL_AMBPEX::StreamParam::status, StreamDestroy(), CL_AMBPEX::StreamParam::system, and CL_AMBPEX::StreamParam::trd.
StreamSetTrd()
int CL_AMBPEX::StreamSetTrd (U32 strm, U32 trd)
Definition at line 600 of file CL_AMBPEX.cpp.
References CL_AMBPEX::StreamParam::hStream, m_streamParam, and CL_AMBPEX::StreamParam::status.
StreamStart()
void CL_AMBPEX::StreamStart (U32 strm)
Definition at line 667 of file CL_AMBPEX.cpp.
References CL_AMBPEX::StreamParam::cycle, CL_AMBPEX::StreamParam::hStream, CL_AMBPEX::StreamParam::indexDma, CL_AMBPEX::StreamParam::indexPc, m_streamParam, RegPeekInd(), CL_AMBPEX::StreamParam::status, CL_AMBPEX::StreamParam::statusStart, StreamStop(), and CL_AMBPEX::StreamParam::trd.
Referenced by TF_SourceAdc::EventStartCycle().
StreamStartEx()
void CL_AMBPEX::StreamStartEx (U32 strm)
Definition at line 699 of file CL_AMBPEX.cpp.
References CL_AMBPEX::StreamParam::cycle, CL_AMBPEX::StreamParam::hStream, CL_AMBPEX::StreamParam::indexDma, CL_AMBPEX::StreamParam::indexPc, m_streamParam, CL_AMBPEX::StreamParam::status, and CL_AMBPEX::StreamParam::statusStart.
StreamStop()
void CL_AMBPEX::StreamStop (U32 strm)
Definition at line 733 of file CL_AMBPEX.cpp.
References CL_AMBPEX::StreamParam::hStream, CL_AMBPEX::StreamParam::indexDma, CL_AMBPEX::StreamParam::indexPc, m_streamParam, RegPokeInd(), CL_AMBPEX::StreamParam::status, CL_AMBPEX::StreamParam::statusStart, and CL_AMBPEX::StreamParam::trd.
Referenced by TF_SourceAdc::ReStartSession(), StreamDestroy(), and StreamStart().
StreamStopEx()
void CL_AMBPEX::StreamStopEx (U32 strm)
Definition at line 762 of file CL_AMBPEX.cpp.
References CL_AMBPEX::StreamParam::hStream, CL_AMBPEX::StreamParam::indexDma, CL_AMBPEX::StreamParam::indexPc, m_streamParam, CL_AMBPEX::StreamParam::status, and CL_AMBPEX::StreamParam::statusStart.
Member Data Documentation
info
BRD_Info CL_AMBPEX::info
Информация о модуле
Definition at line 110 of file CL_AMBPEX.h.
Referenced by init().
m_blkPhysAdr
U64 CL_AMBPEX::m_blkPhysAdr private
Физический адрес окна памяти 0 в ПЛИС - блоки управления
Definition at line 34 of file CL_AMBPEX.h.
Referenced by GetPhysAdr(), and init().
m_hBrd
BRD_Handle CL_AMBPEX::m_hBrd private
Definition at line 29 of file CL_AMBPEX.h.
Referenced by CL_AMBPEX(), GetHandle(), GetSrvHandle(), init(), ShowServiceList(), and ~CL_AMBPEX().
m_hReg
BRD_Handle CL_AMBPEX::m_hReg private
Дескриптор служды для обращения к регистрам
Definition at line 148 of file CL_AMBPEX.h.
Referenced by GetHandleReg(), init(), PkgCmdExecute(), RegPeekDir(), RegPeekInd(), RegPokeDir(), and RegPokeInd().
m_isInit
int CL_AMBPEX::m_isInit =0 static private
1 - выполнена функция BRD_Init
Definition at line 27 of file CL_AMBPEX.h.
Referenced by init().
m_nLid
U32 CL_AMBPEX::m_nLid private
Логический идентификатор модуля
Definition at line 32 of file CL_AMBPEX.h.
Referenced by init(), and ShowBrdInfo().
m_streamParam
StreamParam CL_AMBPEX::m_streamParam[4] private
Definition at line 177 of file CL_AMBPEX.h.
Referenced by StreamDestroy(), StreamDestroyEx(), StreamGetBuf(), StreamGetBufByNum(), StreamGetBufDone(), StreamGetHandle(), StreamGetIndexDma(), StreamGetNextIndex(), StreamGetStub(), StreamInit(), StreamInit_Mode8(), StreamSetTrd(), StreamStart(), StreamStartEx(), StreamStop(), and StreamStopEx().
m_trdPhysAdr
U64 CL_AMBPEX::m_trdPhysAdr private
Физический адрес окна памяти 1 в ПЛИС - тетрады
Definition at line 36 of file CL_AMBPEX.h.
Referenced by GetPhysAdr(), and init().
td
cl_ambpex_task_data* CL_AMBPEX::td private
внутренние данные класса
Definition at line 38 of file CL_AMBPEX.h.
Referenced by CL_AMBPEX(), PkgCmdExecute(), PkgCmdPeekDir(), PkgCmdPeekInd(), PkgCmdPokeDir(), PkgCmdPokeInd(), PkgCmdStart(), and ~CL_AMBPEX().
The documentation for this class was generated from the following files:
E:/_github/simulink_sm/simulink_adc/src/work/CL_AMBPEX.h
E:/_github/simulink_sm/simulink_adc/src/work/CL_AMBPEX.cpp