SM_ADC: Input ports managing methods
Input ports managing methods
Functions
static double BaseBlock::getInputDouble (int port)
static double BaseBlock::getInputInt (int port)
static Array BaseBlock::getInputArray (int port)
static int BaseBlock::getInputWidth (int port)
static int BaseBlock::getInputNRows (int port)
static int BaseBlock::getInputNCols (int port)
static void BaseBlock::setInputPortDimensions (int port, int nrows, int ncols)
Detailed Description
Function Documentation
getInputArray()
static Array BaseBlock::getInputArray (int port) inline static
Returns the input port Array.
Definition at line 343 of file baseblock.h.
References BaseBlock::simStruct, and toString().
Referenced by Block::derivatives(), and Block::outputs().
getInputDouble()
static double BaseBlock::getInputDouble (int port) inline static
Returns the scalar value of an input port.
Definition at line 326 of file baseblock.h.
References BaseBlock::simStruct.
Referenced by Block::outputs().
getInputInt()
static double BaseBlock::getInputInt (int port) inline static
Returns the integer value of an input port
Definition at line 334 of file baseblock.h.
References BaseBlock::simStruct.
getInputNCols()
static int BaseBlock::getInputNCols (int port) inline static
Returns the input port number of cols.
Definition at line 369 of file baseblock.h.
References BaseBlock::simStruct.
getInputNRows()
static int BaseBlock::getInputNRows (int port) inline static
Returns the input port number of rows.
Definition at line 361 of file baseblock.h.
References BaseBlock::simStruct.
getInputWidth()
static int BaseBlock::getInputWidth (int port) inline static
Returns the input port number of elements. If the input port is a 1-D array with w elements, this function returns w. If the input port is an M-by-N array, this function returns m*n.
Definition at line 353 of file baseblock.h.
References BaseBlock::simStruct.
setInputPortDimensions()
static void BaseBlock::setInputPortDimensions (int port, int nrows, int ncols) inline static
Sets the input port dimensions. Must be used only in initializeInputPortSizes
Definition at line 378 of file baseblock.h.
References BaseBlock::simStruct.
Referenced by Block::initializeInputPortSizes(), and BaseBlock::initializeInputPortSizes().