SIMULINK_A7DAC: CL_Reg Class Reference
CL_Reg Class Reference
Доступ к регистраи
#include <cl_reg.h>
Public Member Functions
CL_Reg ()
virtual ~CL_Reg ()
virtual void PkgCmdStart (void)
Начало выполнения команды
virtual void PkgCmdWrite (int dev, int adr, int data)
Запись в регистр
virtual void PkgCmdRead (int dev, int adr, int *pData)
Чтение из регистра
virtual void PkgCmdExecute (void)
Выполнение команды
Detailed Description
Доступ к регистраи
Definition at line 13 of file cl_reg.h.
Constructor & Destructor Documentation
CL_Reg()
CL_Reg::CL_Reg () inline
Definition at line 18 of file cl_reg.h.
~CL_Reg()
virtual CL_Reg::~CL_Reg () inline virtual
Definition at line 19 of file cl_reg.h.
Member Function Documentation
PkgCmdExecute()
virtual void CL_Reg::PkgCmdExecute (void) inline virtual
Выполнение команды
Reimplemented in TF_A7Dac.
Definition at line 31 of file cl_reg.h.
Referenced by TF_DDS::DacStart(), TF_DDS::isPeriodComplete(), TF_PLL::Prepare(), TF_DDS::Prepare(), TF_DDS::SetCntStart(), TF_DDS::SetDacFreq(), TF_PLL::SetDiv(), and TF_PLL::SetPll().
PkgCmdRead()
virtual void CL_Reg::PkgCmdRead (int dev, int adr, int * pData) inline virtual
Чтение из регистра
Reimplemented in TF_A7Dac.
Definition at line 28 of file cl_reg.h.
Referenced by TF_DDS::isPeriodComplete(), TF_PLL::Prepare(), and TF_DDS::Prepare().
PkgCmdStart()
virtual void CL_Reg::PkgCmdStart (void) inline virtual
Начало выполнения команды
Reimplemented in TF_A7Dac.
Definition at line 22 of file cl_reg.h.
Referenced by TF_DDS::DacStart(), TF_DDS::isPeriodComplete(), TF_PLL::Prepare(), TF_DDS::Prepare(), TF_DDS::SetCntStart(), TF_DDS::SetDacFreq(), TF_PLL::SetDiv(), and TF_PLL::SetPll().
PkgCmdWrite()
virtual void CL_Reg::PkgCmdWrite (int dev, int adr, int data) inline virtual
Запись в регистр
Reimplemented in TF_A7Dac.
Definition at line 25 of file cl_reg.h.
Referenced by TF_DDS::DacStart(), TF_PLL::Prepare(), TF_DDS::Prepare(), TF_DDS::SetCntStart(), TF_DDS::SetDacFreq(), TF_PLL::SetDiv(), and TF_PLL::SpdWrite().
The documentation for this class was generated from the following file:
E:/_github/simulink_sm/simulink_a7dac/src/work/cl_reg.h