SIMULINK_ADC: E:/_github/simulink_sm/simulink_adc/src/work/exceptinfo.cpp File Reference
exceptinfo.cpp File Reference
#include "exceptinfo.h"
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <signal.h>
Functions
except_info_t except_info (const BRDCHAR *fmt,...)
Function Documentation
except_info()
except_info_t except_info (const BRDCHAR * fmt, ...)
Definition at line 26 of file exceptinfo.cpp.
References _except_info_t::msg.
Referenced by CL_AMBPEX::PkgCmdExecute(), CL_AMBPEX::PkgCmdPeekDir(), CL_AMBPEX::PkgCmdPeekInd(), CL_AMBPEX::PkgCmdPokeDir(), and CL_AMBPEX::PkgCmdPokeInd().