SM_CTRL: E:/_github/simulink_sm/simulink_sm/src/easyLink-3.3.0/include/utils.h File Reference
utils.h File Reference
#include <iostream>
#include <string>
#include <sstream>
#include <math.h>
#include <vector>
Macros
#define EQUALITY_TOLERANCE 0.00000000000001
Functions
template<typename T >
string toString (T value)
bool isIdentifier (string str)
unsigned long getComputerTime ()
bool areEqual (double x, double y, double tolerance=EQUALITY_TOLERANCE)
Variables
static char ERROR_MSG_BUFFER [512]
Macro Definition Documentation
EQUALITY_TOLERANCE
#define EQUALITY_TOLERANCE 0.00000000000001
Definition at line 85 of file utils.h.
Function Documentation
areEqual()
bool areEqual (double x, double y, double tolerance = EQUALITY_TOLERANCE) inline
Returns true if x are equal to y. The test takes into account the precision of the mantissa.
Definition at line 91 of file utils.h.
Referenced by Array::operator==().
getComputerTime()
unsigned long getComputerTime () inline
Returns the current computer time in milliseconds.
Definition at line 66 of file utils.h.
isIdentifier()
bool isIdentifier (string str) inline
Returns true if the string is a valid MATLAB variable identifier.
Definition at line 45 of file utils.h.
Referenced by BaseBlock::checkParameters(), and BaseFunction::initializeInputPortSizes().
toString()
template<typename T > string toString (T value) inline
Converts a double, int or char to a String.
Definition at line 35 of file utils.h.
Referenced by Array::callMatlab(), BaseBlock::checkParameters(), Array::getFullName(), BaseFunction::getInputArray(), BaseBlock::getInputArray(), BaseFunction::getOutputArray(), BaseBlock::getOutputArray(), BaseBlock::getParameterArray(), BaseFunction::initializeInputPortSizes(), BaseBlock::initializeInputPortSizes(), BaseFunction::initializeOutputPortSizes(), BaseBlock::initializeOutputPortSizes(), BaseBlock::initializeParameterPortSizes(), Array::operator()(), Array::operator*(), Array::operator+(), Array::operator-(), Array::operator/(), Array::operator[](), BaseFunction::setOutputArray(), and BaseBlock::setOutputArray().
Variable Documentation
ERROR_MSG_BUFFER
char ERROR_MSG_BUFFER[512] static
Definition at line 30 of file utils.h.
Referenced by mdlCheckParameters(), mdlDerivatives(), mdlInitializeSampleTimes(), mdlInitializeSizes(), mdlOutputs(), mdlSetInputPortDimensionInfo(), mdlSetOutputPortDimensionInfo(), mdlStart(), mdlTerminate(), mdlUpdate(), mdlZeroCrossings(), and mexFunction().