SM_CTRL: Function Class Reference
Function Class Reference
Static Public Member Functions
static void outputs ()
Static Public Member Functions inherited from BaseFunction
static void initializeInputPortSizes ()
static void initializeOutputPortSizes ()
static void outputs ()
static double getInputDouble (int port)
static double getInputInt (int port)
static Array getInputArray (int port)
static string getInputString (int port)
static int getInputWidth (int port)
static int getInputNRows (int port)
static int getInputNCols (int port)
static void setOutputDouble (int port, double value)
static void setOutputArray (int port, Array &array)
static Array getOutputArray (int port)
static int getOutputWidth (int port)
static int getOutputNRows (int port)
static int getOutputNCols (int port)
static void setOutputPortDimensions (int port, int nrows, int ncols)
Additional Inherited Members
Static Public Attributes inherited from BaseFunction
static int nrhs =0
static const mxArray ** prhs =NULL
static int nlhs =0
static vector< mxArray * > plhs
Detailed Description
Definition at line 46 of file mex_array_product.cpp.
Member Function Documentation
outputs()
static void Function::outputs () inline static
Definition at line 52 of file mex_array_product.cpp.
References BaseFunction::getInputArray(), BaseFunction::getInputDouble(), BaseFunction::getInputNCols(), BaseFunction::getOutputArray(), MATRIX, MULTIPLIER, RESULT, and BaseFunction::setOutputPortDimensions().
Referenced by mexFunction().
The documentation for this class was generated from the following file:
E:/_github/simulink_sm/simulink_sm/src/easyLink-3.3.0/mex_array_product.cpp