SM_ADC: Matlab variables managing methods
Matlab variables managing methods
Functions
Array getMatlabArray (string name, string workspace="base")
bool existMatlabArray (string name, string workspace="base")
Array newMatlabArray (int nrows, int ncols, string name, string workspace="base")
Detailed Description
Function Documentation
existMatlabArray()
bool existMatlabArray (string name, string workspace = "base") inline
Returns true if a MATLAB variable exists with the given name in a given workspace. Works only with double array. Values for workspace are: "base", "caller" or "global".
Definition at line 40 of file matlabarray.h.
getMatlabArray()
Array getMatlabArray (string name, string workspace = "base") inline
Returns an Array connected to a MATLAB variable in a given workspace. Works only with double array. Values for workspace are: "base", "caller" or "global".
Definition at line 23 of file matlabarray.h.
Referenced by newMatlabArray(), and Block::outputs().
newMatlabArray()
Array newMatlabArray (int nrows, int ncols, string name, string workspace = "base") inline
Create a new variable in a given MATALB workspace ("base" is the default workspace) and returns an Array connected this variable. Values for workspace are: "base", "caller" or "global".
Definition at line 55 of file matlabarray.h.
References getMatlabArray().
Referenced by Block::start().