SIMULINK_A7DAC: E:/_github/simulink_sm/simulink_a7dac/src/work/main.cpp File Reference
main.cpp File Reference
#include "stdafx.h"
#include <locale.h>
#include "ConsoleTestApi.h"
#include "TableApi.h"
#include "TF_Test.h"
#include "TF_SimulinkA7Dac.h"
Functions
int BRDC_main (int argc, BRDCHAR *argv[])
Variables
U32 g_isTStudio =0
HANDLE hConsoleOut
Function Documentation
BRDC_main()
int BRDC_main (int argc, BRDCHAR * argv[])
Definition at line 50 of file main.cpp.
References CreateTable(), g_isTStudio, TF_Test::GetResult(), hConsoleOut, TF_Test::isComplete(), kbhit_ex(), PARSE_CMDLINE_DEC, ParseCommandLine(), TF_Test::Prepare(), TF_Test::Start(), StartSignal(), StdoutFlushAndSetBufNull(), TF_Test::Step(), TF_Test::Stop(), and StopSignal().
Variable Documentation
g_isTStudio
U32 g_isTStudio =0
Definition at line 42 of file main.cpp.
Referenced by BRDC_main().
hConsoleOut
HANDLE hConsoleOut
Definition at line 47 of file main.cpp.
Referenced by BRDC_main().