SIMULINK_A7DAC: TF_DDS Class Reference
TF_DDS Class Reference
Формирование сигнала
#include <tf_dds.h>
Public Member Functions
TF_DDS (CL_Reg *reg)
virtual ~TF_DDS ()
void Prepare (int flagLoadSinTable)
Подготовка
void SetDacFreq (double syntFreq, double Freq0, double Phase0, double Ampl0, double Freq1, double Phase1, double Ampl1)
Установка частоты
void SetPhase (double syntFreq, double Freq, double Phase, __int64 &phase_start, __int64 &phase_inc)
void SetCntStart (int regCntEnable, int regCntDisable, int regPeriod, int isContinuePeriod, int isCntEnable)
Установка счётчиков старта
int isPeriodComplete (void)
Завершение вывода
void DacStart (int enable, int start)
Запуск и останов
Private Attributes
TF_DDS_TaskData * td
Внутренние данные класса
Detailed Description
Формирование сигнала
Definition at line 17 of file tf_dds.h.
Constructor & Destructor Documentation
TF_DDS()
TF_DDS::TF_DDS (CL_Reg * reg)
Definition at line 23 of file tf_dds.cpp.
References TF_DDS_TaskData::reg, and td.
~TF_DDS()
TF_DDS::~TF_DDS () virtual
Definition at line 30 of file tf_dds.cpp.
References td.
Member Function Documentation
DacStart()
void TF_DDS::DacStart (int enable, int start)
Запуск и останов
Definition at line 233 of file tf_dds.cpp.
References CL_Reg::PkgCmdExecute(), CL_Reg::PkgCmdStart(), CL_Reg::PkgCmdWrite(), TF_DDS_TaskData::reg, and td.
Referenced by TF_A7DacCtrl::EventStartCycle(), TF_A7DacCtrl::isCycleCompletion(), and TF_A7DacCtrl::ReStartSession().
isPeriodComplete()
int TF_DDS::isPeriodComplete (void)
Завершение вывода
Definition at line 218 of file tf_dds.cpp.
References CL_Reg::PkgCmdExecute(), CL_Reg::PkgCmdRead(), CL_Reg::PkgCmdStart(), TF_DDS_TaskData::reg, and td.
Referenced by TF_A7DacCtrl::isCycleCompletion(), and SetCntStart().
Prepare()
void TF_DDS::Prepare (int flagLoadSinTable)
Подготовка
Подготовка PLL.
Definition at line 37 of file tf_dds.cpp.
References CL_Reg::PkgCmdExecute(), CL_Reg::PkgCmdRead(), CL_Reg::PkgCmdStart(), CL_Reg::PkgCmdWrite(), TF_DDS_TaskData::reg, and td.
Referenced by TF_A7DacCtrl::Prepare().
SetCntStart()
void TF_DDS::SetCntStart (int regCntEnable, int regCntDisable, int regPeriod, int isContinuePeriod, int isCntEnable)
Установка счётчиков старта
Definition at line 186 of file tf_dds.cpp.
References isPeriodComplete(), CL_Reg::PkgCmdExecute(), CL_Reg::PkgCmdStart(), CL_Reg::PkgCmdWrite(), TF_DDS_TaskData::reg, and td.
Referenced by TF_A7DacCtrl::EventStartCycle(), and TF_A7DacCtrl::Prepare().
SetDacFreq()
void TF_DDS::SetDacFreq (double syntFreq, double Freq0, double Phase0, double Ampl0, double Freq1, double Phase1, double Ampl1)
Установка частоты
Definition at line 131 of file tf_dds.cpp.
References CL_Reg::PkgCmdExecute(), CL_Reg::PkgCmdStart(), CL_Reg::PkgCmdWrite(), TF_DDS_TaskData::reg, SetPhase(), and td.
Referenced by TF_A7DacCtrl::EventStartCycle(), and TF_A7DacCtrl::Prepare().
SetPhase()
void TF_DDS::SetPhase (double syntFreq, double Freq, double Phase, __int64 & phase_start, __int64 & phase_inc)
Definition at line 120 of file tf_dds.cpp.
Referenced by SetDacFreq().
Member Data Documentation
td
TF_DDS_TaskData* TF_DDS::td private
Внутренние данные класса
Definition at line 20 of file tf_dds.h.
Referenced by DacStart(), isPeriodComplete(), Prepare(), SetCntStart(), SetDacFreq(), TF_DDS(), and ~TF_DDS().
The documentation for this class was generated from the following files:
E:/_github/simulink_sm/simulink_a7dac/src/work/tf_dds.h
E:/_github/simulink_sm/simulink_a7dac/src/work/tf_dds.cpp