SM_ADC: S-function state ports managing methods
S-function state ports managing methods
Functions
static Array BaseBlock::getContinuousStateArray ()
static int BaseBlock::getContinuousStateWidth (int port)
static void BaseBlock::setDerivativeStateArray (Array &array)
static Array BaseBlock::getDiscreteStateArray ()
static int BaseBlock::getDiscreteStateWidth (int port)
static void BaseBlock::setDiscreteStateArray (Array &array)
static void BaseBlock::setContinuousStatesNumber (int num)
static void BaseBlock::setDiscreteStatesNumber (int num)
Detailed Description
Function Documentation
getContinuousStateArray()
static Array BaseBlock::getContinuousStateArray () inline static
Returns the continuous state Array.
Definition at line 522 of file baseblock.h.
References BaseBlock::simStruct.
Referenced by Block::derivatives(), and Block::outputs().
getContinuousStateWidth()
static int BaseBlock::getContinuousStateWidth (int port) inline static
Returns the continuous state number of elements (1-D array).
Definition at line 530 of file baseblock.h.
References BaseBlock::simStruct.
getDiscreteStateArray()
static Array BaseBlock::getDiscreteStateArray () inline static
Returns the discrete state Array.
Definition at line 552 of file baseblock.h.
References BaseBlock::simStruct.
getDiscreteStateWidth()
static int BaseBlock::getDiscreteStateWidth (int port) inline static
Returns the discrete state number of elements (1-D array).
Definition at line 560 of file baseblock.h.
References BaseBlock::simStruct.
setContinuousStatesNumber()
static void BaseBlock::setContinuousStatesNumber (int num) inline static
Sets the number of continuous states. Must be used in lastMinuteSizeChanges.
Definition at line 582 of file baseblock.h.
References BaseBlock::simStruct.
Referenced by Block::initializeStatePortSizes().
setDerivativeStateArray()
static void BaseBlock::setDerivativeStateArray (Array & array) inline static
Writes the derivative state Array.
Definition at line 538 of file baseblock.h.
References Array::getData(), Array::getName(), Array::getNCols(), Array::getNRows(), Array::getWidth(), and BaseBlock::simStruct.
Referenced by Block::derivatives().
setDiscreteStateArray()
static void BaseBlock::setDiscreteStateArray (Array & array) inline static
Writes the discrete state Array.
Definition at line 568 of file baseblock.h.
References Array::getData(), Array::getName(), Array::getNCols(), Array::getNRows(), Array::getWidth(), and BaseBlock::simStruct.
setDiscreteStatesNumber()
static void BaseBlock::setDiscreteStatesNumber (int num) inline static
Sets the number of discrete states. Must be used in lastMinuteSizeChanges.
Definition at line 590 of file baseblock.h.
References BaseBlock::simStruct.