SIMULINK_A7DAC: E:/_github/simulink_sm/simulink_a7dac/src/ConsoleTestApi/ConsoleTestApi.h File Reference
ConsoleTestApi.h File Reference
#include "utypes.h"
Classes
struct TParse
Enumerations
enum {
PARSE_CMDLINE_HEX = 0, PARSE_CMDLINE_DEC = 1, PARSE_CMDLINE_FLOAT = 2, PARSE_CMDLINE_64_BIT = 3,
PARSE_CMDLINE_STRING = 4, PARSE_CMDLINE_TOGGLE = 5
}
Functions
void StdoutFlushAndSetBufNull ()
int kbhit_ex (int isFlg)
void ParseCommandLine (int argc, BRDCHAR *argv[], TParse arParse[], int nCnt)
void StartSignal (int isTStudio)
void StopSignal (int isTStudio)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PARSE_CMDLINE_HEX
PARSE_CMDLINE_DEC
PARSE_CMDLINE_FLOAT
PARSE_CMDLINE_64_BIT
PARSE_CMDLINE_STRING
PARSE_CMDLINE_TOGGLE
Definition at line 5 of file ConsoleTestApi.h.
Function Documentation
kbhit_ex()
int kbhit_ex (int isFlg)
Definition at line 23 of file ConsoleTestApi.cpp.
Referenced by BRDC_main().
ParseCommandLine()
void ParseCommandLine (int argc, BRDCHAR * argv[], TParse arParse[], int nCnt)
Definition at line 48 of file ConsoleTestApi.cpp.
References PARSE_CMDLINE_DEC, PARSE_CMDLINE_FLOAT, PARSE_CMDLINE_HEX, PARSE_CMDLINE_STRING, and PARSE_CMDLINE_TOGGLE.
Referenced by BRDC_main().
StartSignal()
void StartSignal (int isTStudio)
Definition at line 109 of file ConsoleTestApi.cpp.
Referenced by BRDC_main().
StdoutFlushAndSetBufNull()
void StdoutFlushAndSetBufNull ()
Definition at line 12 of file ConsoleTestApi.cpp.
Referenced by BRDC_main().
StopSignal()
void StopSignal (int isTStudio)
Definition at line 116 of file ConsoleTestApi.cpp.
Referenced by BRDC_main().