SM_ADC: S-function initialization methods
S-function initialization methods
Functions
static void BaseBlock::initializeParameterPortSizes ()
static void BaseBlock::initializeInputPortSizes ()
static void BaseBlock::initializeOutputPortSizes ()
static void BaseBlock::initializeStatePortSizes ()
static void BaseBlock::initializeNumberSampleTimes ()
static void BaseBlock::initializeOptions ()
static void BaseBlock::setInputPortDimensionInfo (int port, const DimsInfo_T *dimsInfo)
static void BaseBlock::setOutputPortDimensionInfo (int port, const DimsInfo_T *dimsInfo)
static void BaseBlock::checkParameters ()
static void BaseBlock::initializeSampleTimes ()
Detailed Description
Function Documentation
checkParameters()
static void BaseBlock::checkParameters () inline static
This static method is called with candidate parameter values. If the proposed dimensions or types are unacceptable, the method must throw an exception.
The possible types of the paramaters are:
1 for real parameters (scalar or array, use -1 as size to specify a dynamically dimensioned array)
2 for literal string parameters
3 for literal identifiers of MATLAB variables
For more information, see: http://www.mathworks.fr/fr/help/simulink/sfg/mdlcheckparameters.html
Definition at line 201 of file baseblock.h.
References BaseBlock::getParameterString(), isIdentifier(), PARAMETER_NUMBER, parameterCols, parameterRows, parameterType, BaseBlock::simStruct, and toString().
Referenced by mdlCheckParameters().
initializeInputPortSizes()
static void BaseBlock::initializeInputPortSizes () inline static
This is the second static method that the Simulink engine calls within mdlInitializeSizes. This method specifies the number of input ports and their dimensions. All ports are set to direct feedthrough by default.
Use -1 to specify dynamically dimensioned input signals.
For more information, see: http://www.mathworks.fr/fr/help/simulink/sfg/mdlinitializesizes.html
Definition at line 95 of file baseblock.h.
References INPUT_PORT_NUMBER, inputPortCols, inputPortRows, BaseBlock::setInputPortDimensions(), BaseBlock::simStruct, and toString().
initializeNumberSampleTimes()
static void BaseBlock::initializeNumberSampleTimes () inline static
This is the fifth static method that the Simulink engine calls within mdlInitializeSizes. This method specifies the number of sample time (i.e., sample rates) at which the block operates.
The default value is 1
For more information, see: http://www.mathworks.fr/fr/help/simulink/sfg/mdlinitializesizes.html
Definition at line 148 of file baseblock.h.
References BaseBlock::simStruct.
Referenced by mdlInitializeSizes().
initializeOptions()
static void BaseBlock::initializeOptions () inline static
This is the sixth static method that the Simulink engine calls within mdlInitializeSizes. This method specifies the simulation options that this block implements, using ssSetOptions.
For more information, see: http://www.mathworks.fr/fr/help/simulink/sfg/mdlinitializesizes.html
Definition at line 162 of file baseblock.h.
Referenced by mdlInitializeSizes().
initializeOutputPortSizes()
static void BaseBlock::initializeOutputPortSizes () inline static
This is the third static method that the Simulink engine calls within mdlInitializeSizes. This method specifies the number of output ports and their dimensions.
Use -1 to specify dynamically dimensioned output signals.
For more information, see: http://www.mathworks.fr/fr/help/simulink/sfg/mdlinitializesizes.html
Definition at line 116 of file baseblock.h.
References OUTPUT_PORT_NUMBER, outputPortCols, outputPortRows, BaseBlock::setOutputPortDimensions(), BaseBlock::simStruct, and toString().
Referenced by Block::initializeOutputPortSizes().
initializeParameterPortSizes()
static void BaseBlock::initializeParameterPortSizes () inline static
This is the first static method that the Simulink engine calls within mdlInitializeSizes. This method specifies the number of parameters and wheter or not they are tunable. A parameter is tunable if its value can change during simulation.
Use -1 to specify dynamically dimensioned parameters.
For more information, see: http://www.mathworks.fr/fr/help/simulink/sfg/mdlinitializesizes.html
Definition at line 73 of file baseblock.h.
References PARAMETER_NUMBER, parameterTunable, BaseBlock::simStruct, and toString().
initializeSampleTimes()
static void BaseBlock::initializeSampleTimes () inline static
This static method should specify the sample time and offset time for each sample rate at which this S-function operates.
The default values are INHERITED_SAMPLE_TIME and FIXED_IN_MINOR_STEP_OFFSET
For more information, see: http://www.mathworks.fr/fr/help/simulink/sfg/mdlinitializesampletimes.html
Definition at line 243 of file baseblock.h.
References BaseBlock::simStruct.
initializeStatePortSizes()
static void BaseBlock::initializeStatePortSizes () inline static
This is the fourth static method that the Simulink engine calls within mdlInitializeSizes. This method specifies the number of continuous and discrete states.
The default values are zero continuous states and zero discrete states.
For more information, see: http://www.mathworks.fr/fr/help/simulink/sfg/mdlinitializesizes.html
Definition at line 133 of file baseblock.h.
References BaseBlock::simStruct.
setInputPortDimensionInfo()
static void BaseBlock::setInputPortDimensionInfo (int port, const DimsInfo_T * dimsInfo) inline static
This static method is called with candidate dimensions for input port. If the proposed dimensions are unacceptable for the port, the method must throw an exception.
For more information, see: http://www.mathworks.fr/fr/help/simulink/sfg/mdlsetinputportdimensioninfo.html
Definition at line 172 of file baseblock.h.
References BaseBlock::simStruct.
Referenced by Block::setInputPortDimensionInfo().
setOutputPortDimensionInfo()
static void BaseBlock::setOutputPortDimensionInfo (int port, const DimsInfo_T * dimsInfo) inline static
This static method is called with candidate dimensions for output port. If the proposed dimensions are unacceptable for the port, the method must throw an exception.
For more information, see: http://www.mathworks.fr/fr/help/simulink/sfg/mdlsetoutputportdimensioninfo.html
Definition at line 183 of file baseblock.h.
References BaseBlock::simStruct.
Referenced by mdlSetOutputPortDimensionInfo(), and Block::setInputPortDimensionInfo().