SIMULINK_A7DAC: TF_DacTop Class Reference
TF_DacTop Class Reference
#include <tf_dactop.h>
Public Slots
void doWork ()
void updateParam ()
void onTimer ()
Шаг опроса изменения параметров
Public Member Functions
TF_DacTop ()
~TF_DacTop ()
Private Member Functions
void mainLoop ()
Основной цикл опроса
Private Attributes
TF_DacTop_TaskData * td
Внутренние данные класса
Detailed Description
Definition at line 11 of file tf_dactop.h.
Constructor & Destructor Documentation
TF_DacTop()
TF_DacTop::TF_DacTop ()
Definition at line 37 of file tf_dactop.cpp.
References td.
~TF_DacTop()
TF_DacTop::~TF_DacTop ()
Definition at line 42 of file tf_dactop.cpp.
References td.
Member Function Documentation
doWork
void TF_DacTop::doWork () slot
Definition at line 47 of file tf_dactop.cpp.
References TF_DacTop_TaskData::a7dac, TF_DacTop_TaskData::dds, onTimer(), TF_A7Dac::Open(), TF_A7Dac::PkgCmdExecute(), TF_A7Dac::PkgCmdRead(), TF_A7Dac::PkgCmdStart(), TF_A7Dac::PkgCmdWrite(), TF_DacTop_TaskData::pll, TF_PLL::Prepare(), TF_DDS::Prepare(), TF_PLL::SetPll(), td, and TF_DacTop_TaskData::timer.
mainLoop()
void TF_DacTop::mainLoop () private
Основной цикл опроса
Definition at line 115 of file tf_dactop.cpp.
onTimer
void TF_DacTop::onTimer () slot
Шаг опроса изменения параметров
Definition at line 136 of file tf_dactop.cpp.
References TF_GlobalParam::dac0Ampl, TF_GlobalParam::dac0Freq, TF_GlobalParam::dac0Phase, TF_GlobalParam::dac1Ampl, TF_GlobalParam::dac1Freq, TF_GlobalParam::dac1Phase, TF_DacTop_TaskData::dds, TF_GlobalParam::divA, TF_GlobalParam::divB, TF_GlobalParam::freqDac, TF_GlobalParam::freqExternal, TF_GlobalParam::freqSynt, g_GlobalParam, TF_PLL::GetFreq(), TF_GlobalParam::is_chageFreq, TF_GlobalParam::is_dacChange, TF_GlobalParam::is_divA, TF_GlobalParam::is_divB, TF_GlobalParam::is_freqSynt, TF_DacTop_TaskData::pll, TF_DDS::SetDacFreq(), TF_PLL::SetDiv(), TF_PLL::SetPll(), and td.
Referenced by doWork().
updateParam
void TF_DacTop::updateParam () slot
Definition at line 130 of file tf_dactop.cpp.
Member Data Documentation
td
TF_DacTop_TaskData* TF_DacTop::td private
Внутренние данные класса
Definition at line 16 of file tf_dactop.h.
Referenced by doWork(), onTimer(), TF_DacTop(), and ~TF_DacTop().
The documentation for this class was generated from the following files:
E:/_github/simulink_sm/simulink_a7dac/src/work/tf_dactop.h
E:/_github/simulink_sm/simulink_a7dac/src/work/tf_dactop.cpp