SIMULINK_A7DAC: TF_A7Dac Class Reference
TF_A7Dac Class Reference
Управление модулем A7_Dac.
#include <tf_a7dac.h>
Public Member Functions
TF_A7Dac ()
virtual ~TF_A7Dac ()
int Open (void)
Начало работы с модулем
virtual void PkgCmdStart (void)
Начало выполнения команды
virtual void PkgCmdWrite (int dev, int adr, int data)
Запись в регистр
virtual void PkgCmdRead (int dev, int adr, int *pData)
Чтение из регистра
virtual void PkgCmdExecute (void)
Выполнение команды
int GetPldDone (void)
Проверка наличия прошивки
int PldLoad (char *fname)
Загрузка прошивки ПЛИС
Public Member Functions inherited from CL_Reg
CL_Reg ()
virtual ~CL_Reg ()
Private Attributes
TF_A7Dac_TaskData * td
Внутренние данные класса
Detailed Description
Управление модулем A7_Dac.
Definition at line 14 of file tf_a7dac.h.
Constructor & Destructor Documentation
TF_A7Dac()
TF_A7Dac::TF_A7Dac ()
Definition at line 34 of file tf_a7dac.cpp.
References td.
~TF_A7Dac()
TF_A7Dac::~TF_A7Dac () virtual
Definition at line 39 of file tf_a7dac.cpp.
References td.
Member Function Documentation
GetPldDone()
int TF_A7Dac::GetPldDone (void)
Проверка наличия прошивки
Definition at line 167 of file tf_a7dac.cpp.
References TF_A7Dac_TaskData::ftHandle, and td.
Referenced by Open().
Open()
int TF_A7Dac::Open (void)
Начало работы с модулем
Definition at line 45 of file tf_a7dac.cpp.
References TF_A7Dac_TaskData::ftHandle, GetPldDone(), PkgCmdExecute(), PkgCmdRead(), PkgCmdStart(), PldLoad(), and td.
Referenced by TF_A7DacCtrl::Prepare().
PkgCmdExecute()
void TF_A7Dac::PkgCmdExecute (void) virtual
Выполнение команды
Reimplemented from CL_Reg.
Definition at line 337 of file tf_a7dac.cpp.
References CMD_Item::adr, CMD_Item::cmd, TF_A7Dac_TaskData::cmd_index, CMD_Item::data, CMD_Item::dev, TF_A7Dac_TaskData::ftHandle, TF_A7Dac_TaskData::items, CMD_Item::pData, and td.
Referenced by Open(), and TF_A7DacCtrl::Prepare().
PkgCmdRead()
void TF_A7Dac::PkgCmdRead (int dev, int adr, int * pData) virtual
Чтение из регистра
Reimplemented from CL_Reg.
Definition at line 323 of file tf_a7dac.cpp.
References CMD_Item::adr, CMD_Item::cmd, TF_A7Dac_TaskData::cmd_index, CMD_Item::data, CMD_Item::dev, TF_A7Dac_TaskData::items, CMD_Item::pData, and td.
Referenced by Open(), and TF_A7DacCtrl::Prepare().
PkgCmdStart()
void TF_A7Dac::PkgCmdStart (void) virtual
Начало выполнения команды
Reimplemented from CL_Reg.
Definition at line 302 of file tf_a7dac.cpp.
References TF_A7Dac_TaskData::cmd_index, TF_A7Dac_TaskData::cmd_status, and td.
Referenced by Open(), and TF_A7DacCtrl::Prepare().
PkgCmdWrite()
void TF_A7Dac::PkgCmdWrite (int dev, int adr, int data) virtual
Запись в регистр
Reimplemented from CL_Reg.
Definition at line 309 of file tf_a7dac.cpp.
References CMD_Item::adr, CMD_Item::cmd, TF_A7Dac_TaskData::cmd_index, CMD_Item::data, CMD_Item::dev, TF_A7Dac_TaskData::items, CMD_Item::pData, and td.
Referenced by TF_A7DacCtrl::Prepare().
PldLoad()
int TF_A7Dac::PldLoad (char * fname)
Загрузка прошивки ПЛИС
Definition at line 207 of file tf_a7dac.cpp.
References TF_A7Dac_TaskData::ftHandle, and td.
Referenced by Open().
Member Data Documentation
td
TF_A7Dac_TaskData* TF_A7Dac::td private
Внутренние данные класса
Definition at line 18 of file tf_a7dac.h.
Referenced by GetPldDone(), Open(), PkgCmdExecute(), PkgCmdRead(), PkgCmdStart(), PkgCmdWrite(), PldLoad(), TF_A7Dac(), and ~TF_A7Dac().
The documentation for this class was generated from the following files:
E:/_github/simulink_sm/simulink_a7dac/src/work/tf_a7dac.h
E:/_github/simulink_sm/simulink_a7dac/src/work/tf_a7dac.cpp