SIMULINK_A7DAC: E:/_github/simulink_sm/simulink_a7dac/src/ConsoleTestApi/TableApi.h File Reference
TableApi.h File Reference
#include "utypes.h"
Functions
S32 CreateTable (char *pColumnName[], U32 nCount, U08 isTStudio)
S32 AddRowTable ()
S32 SetValueTable (U32 nRow, U32 nColumn, char *pVal)
S32 SetValueTable (U32 nRow, U32 nColumn, S32 nVal, char *format=" %d ")
S32 SetValueTable (U32 nRow, U32 nColumn, U32 nVal, char *format=" %u ")
S32 SetValueTable (U32 nRow, U32 nColumn, REAL64 dVal, char *format=" %f ")
Function Documentation
AddRowTable()
S32 AddRowTable ()
Definition at line 82 of file TableApi.cpp.
References g_isTS, g_nColCount, g_nRowCount, g_nWidthTable, g_paColItems, and TColumnItem::len.
Referenced by TF_SimulinkA7Dac::Start().
CreateTable()
S32 CreateTable (char * pColumnName[], U32 nCount, U08 isTStudio)
Definition at line 25 of file TableApi.cpp.
References g_isTS, g_nColCount, g_nWidthTable, g_nYPosition, g_paColItems, TColumnItem::len, and TColumnItem::posX.
Referenced by BRDC_main().
SetValueTable() [1/4]
S32 SetValueTable (U32 nRow, U32 nColumn, char * pVal)
Definition at line 115 of file TableApi.cpp.
References g_isTS, g_nColCount, g_nRowCount, g_nYPosition, g_paColItems, TColumnItem::len, and TColumnItem::posX.
Referenced by SetValueTable(), and TF_SimulinkA7Dac::Step().
SetValueTable() [2/4]
S32 SetValueTable (U32 nRow, U32 nColumn, S32 nVal, char * format = " %d ")
Definition at line 155 of file TableApi.cpp.
References SetValueTable().
SetValueTable() [3/4]
S32 SetValueTable (U32 nRow, U32 nColumn, U32 nVal, char * format = " %u ")
Definition at line 167 of file TableApi.cpp.
References SetValueTable().
SetValueTable() [4/4]
S32 SetValueTable (U32 nRow, U32 nColumn, REAL64 dVal, char * format = " %f ")
Definition at line 178 of file TableApi.cpp.
References SetValueTable().