SIMULINK_A7DAC: TF_WorkParam Class Reference
TF_WorkParam Class Reference
Класс хранения параметров обработки
#include <TF_WorkParam.h>
Classes
struct STR_CFG
Структура массива параметров
Public Member Functions
TF_WorkParam (void)
~TF_WorkParam (void)
void GetParamFromFile (BRDCHAR *fname)
Получение параметров из файла инициализации
U32 GetParamFromStr (char *str)
Получение параметра из строки
virtual void CalculateParams (void)
Расчёт параметров
U32 PutParamToMemory (char *ptr, U32 max_size)
Сохранение параметров в памяти
void GetParamFromMemory (char *ptr)
Получение параметров из памяти
virtual void SetDefault (void)
Установка параметров по умолчанию
virtual void ShowParam (void)
Отображение параметров
void log_out (char *fmt,...)
Функция отображения параметров
Public Attributes
STR_CFG array_cfg [500]
U32 max_item
Detailed Description
Класс хранения параметров обработки
Класс содержит параметры используемые при обработке. Парметры могут загружаться из файла данных. Каждый парметр может быть установлен с использованием текстовой строки.
Definition at line 27 of file TF_WorkParam.h.
Constructor & Destructor Documentation
TF_WorkParam()
TF_WorkParam::TF_WorkParam (void)
Definition at line 14 of file TF_WorkParam.cpp.
References max_item, and SetDefault().
~TF_WorkParam()
TF_WorkParam::~TF_WorkParam (void)
Definition at line 25 of file TF_WorkParam.cpp.
References array_cfg, max_item, and TF_WorkParam::STR_CFG::ptr.
Member Function Documentation
CalculateParams()
void TF_WorkParam::CalculateParams (void) virtual
Расчёт параметров
Reimplemented in TF_TestStrm, and TF_TestStrmOut.
Definition at line 210 of file TF_WorkParam.cpp.
References ShowParam().
GetParamFromFile()
void TF_WorkParam::GetParamFromFile (BRDCHAR * fname)
Получение параметров из файла инициализации
Definition at line 127 of file TF_WorkParam.cpp.
References GetParamFromStr(), and log_out().
Referenced by TF_TestStrm::TF_TestStrm(), and TF_TestStrmOut::TF_TestStrmOut().
GetParamFromMemory()
void TF_WorkParam::GetParamFromMemory (char * ptr)
Получение параметров из памяти
Definition at line 266 of file TF_WorkParam.cpp.
References GetParamFromStr().
GetParamFromStr()
U32 TF_WorkParam::GetParamFromStr (char * str)
Получение параметра из строки
Definition at line 156 of file TF_WorkParam.cpp.
References array_cfg, max_item, and TF_WorkParam::STR_CFG::ptr.
Referenced by GetParamFromFile(), GetParamFromMemory(), TF_TestStrmOut::SetDefault(), SetDefault(), and TF_TestStrm::SetDefault().
log_out()
void TF_WorkParam::log_out (char * fmt, ...)
Функция отображения параметров
Definition at line 322 of file TF_WorkParam.cpp.
Referenced by GetParamFromFile(), TF_TestStrm::PrepareDDR4(), and ShowParam().
PutParamToMemory()
U32 TF_WorkParam::PutParamToMemory (char * ptr, U32 max_size)
Сохранение параметров в памяти
Definition at line 217 of file TF_WorkParam.cpp.
References array_cfg, TF_WorkParam::STR_CFG::is_float, max_item, TF_WorkParam::STR_CFG::name, and TF_WorkParam::STR_CFG::ptr.
SetDefault()
void TF_WorkParam::SetDefault (void) virtual
Установка параметров по умолчанию
Reimplemented in TF_TestStrm, and TF_TestStrmOut.
Definition at line 45 of file TF_WorkParam.cpp.
References array_cfg, GetParamFromStr(), max_item, and TF_WorkParam::STR_CFG::ptr.
Referenced by TF_WorkParam().
ShowParam()
void TF_WorkParam::ShowParam (void) virtual
Отображение параметров
Reimplemented in TF_TestStrm, and TF_TestStrmOut.
Definition at line 286 of file TF_WorkParam.cpp.
References array_cfg, TF_WorkParam::STR_CFG::is_float, log_out(), max_item, TF_WorkParam::STR_CFG::name, and TF_WorkParam::STR_CFG::ptr.
Referenced by CalculateParams(), TF_TestStrmOut::ShowParam(), and TF_TestStrm::ShowParam().
Member Data Documentation
array_cfg
STR_CFG TF_WorkParam::array_cfg[500]
Definition at line 83 of file TF_WorkParam.h.
Referenced by GetParamFromStr(), PutParamToMemory(), TF_TestStrmOut::SetDefault(), SetDefault(), TF_TestStrm::SetDefault(), ShowParam(), and ~TF_WorkParam().
max_item
U32 TF_WorkParam::max_item
Definition at line 84 of file TF_WorkParam.h.
Referenced by GetParamFromStr(), PutParamToMemory(), TF_TestStrmOut::SetDefault(), SetDefault(), TF_TestStrm::SetDefault(), ShowParam(), TF_WorkParam(), and ~TF_WorkParam().
The documentation for this class was generated from the following files:
E:/_github/simulink_sm/simulink_a7dac/src/work/TF_WorkParam.h
E:/_github/simulink_sm/simulink_a7dac/src/work/TF_WorkParam.cpp