SIMULINK_ADC: TF_SourceAdc Class Reference
TF_SourceAdc Class Reference
Ввод данных от АЦП
#include <TF_SourceAdc.h>
Public Member Functions
TF_SourceAdc (int argc, BRDCHAR **argv)
virtual ~TF_SourceAdc ()
virtual int Prepare (int count)
Prepare function.
virtual void ReStartSession (void)
Start new session of process data.
virtual void EventStartCycle (void)
Start of new data cycle.
virtual int GetData (U32 **ptr)
Get buffer of data.
void PrepareAdc (char *fname)
Подготовка FM214x250M.
Public Member Functions inherited from TF_BaseSource
TF_BaseSource (int argc, BRDCHAR **argv)
virtual ~TF_BaseSource ()
Private Attributes
TF_SourceAdc_TaskData * td
Internal data of TF_SourceAdc.
Detailed Description
Ввод данных от АЦП
Класс принимает данные от АЦП с использованием библиотеки BARDY
Для работы с АЦП должен быть установлен пакет DaqTools для выбранного сочетания базового модуля и субмодуля. http://insys.ru/downloads/daqtools64
В каталоге simulink_adc должен быть файл brd.ini настроенный на сочетание базового модуля и субмодуля и файл exam_adc.ini в котором должны быть установлены параметры АЦП.
Основные функции и классы:
PrepareAdc() - инициализация АЦП
ReStartSession() - перезапуск сеанса сбора, запускается при запуске моделирования в Simulink
EventStartCycle() - запуск сбора
GetData() -получение блока данных
Константа SIZE_DATA_OUT_ARRAY в файле global.h определяет размер собираемого блока данных.
Definition at line 36 of file TF_SourceAdc.h.
Constructor & Destructor Documentation
TF_SourceAdc()
TF_SourceAdc::TF_SourceAdc (int argc, BRDCHAR ** argv)
Definition at line 61 of file TF_SourceAdc.cpp.
References TF_SourceAdc_TaskData::pBrd, and td.
~TF_SourceAdc()
TF_SourceAdc::~TF_SourceAdc () virtual
Definition at line 70 of file TF_SourceAdc.cpp.
References TF_SourceAdc_TaskData::pBrd, CL_AMBPEX::StreamDestroy(), TF_SourceAdc_TaskData::strmNo, and td.
Member Function Documentation
EventStartCycle()
void TF_SourceAdc::EventStartCycle (void) virtual
Start of new data cycle.
Reimplemented from TF_BaseSource.
Definition at line 104 of file TF_SourceAdc.cpp.
References TF_SourceAdc_TaskData::pBrd, CL_AMBPEX::RegPokeInd(), CL_AMBPEX::StreamStart(), TF_SourceAdc_TaskData::strmNo, td, and TF_SourceAdc_TaskData::trd.
GetData()
int TF_SourceAdc::GetData (U32 ** ptr) virtual
Get buffer of data.
Parameters
ptr pointer of pointer of data, output
Returns
1 - set new pointer to ptr
Reimplemented from TF_BaseSource.
Definition at line 116 of file TF_SourceAdc.cpp.
References TF_SourceAdc_TaskData::data, TF_SourceAdc_TaskData::data_out_size, TF_SourceAdc_TaskData::pBrd, CL_AMBPEX::StreamGetBuf(), TF_SourceAdc_TaskData::strmNo, and td.
Prepare()
int TF_SourceAdc::Prepare (int count) virtual
Prepare function.
Reimplemented from TF_BaseSource.
Definition at line 77 of file TF_SourceAdc.cpp.
References TF_SourceAdc_TaskData::cntBuf, TF_SourceAdc_TaskData::cycle, CL_AMBPEX::init(), TF_SourceAdc_TaskData::pBrd, PrepareAdc(), TF_SourceAdc_TaskData::StreamBufSizeOfBytes, CL_AMBPEX::StreamInit(), TF_SourceAdc_TaskData::strmNo, td, and TF_SourceAdc_TaskData::trd.
PrepareAdc()
void TF_SourceAdc::PrepareAdc (char * fname)
Подготовка FM214x250M.
Definition at line 141 of file TF_SourceAdc.cpp.
References AdcSettings(), CL_AMBPEX::GetSrvHandle(), TF_SourceAdc_TaskData::m_hAdc, TF_SourceAdc_TaskData::pBrd, and td.
Referenced by Prepare().
ReStartSession()
void TF_SourceAdc::ReStartSession (void) virtual
Start new session of process data.
Reimplemented from TF_BaseSource.
Definition at line 95 of file TF_SourceAdc.cpp.
References TF_SourceAdc_TaskData::pBrd, CL_AMBPEX::StreamStop(), TF_SourceAdc_TaskData::strmNo, and td.
Member Data Documentation
td
TF_SourceAdc_TaskData* TF_SourceAdc::td private
Internal data of TF_SourceAdc.
Definition at line 40 of file TF_SourceAdc.h.
Referenced by EventStartCycle(), GetData(), Prepare(), PrepareAdc(), ReStartSession(), TF_SourceAdc(), and ~TF_SourceAdc().
The documentation for this class was generated from the following files:
E:/_github/simulink_sm/simulink_adc/src/work/TF_SourceAdc.h
E:/_github/simulink_sm/simulink_adc/src/work/TF_SourceAdc.cpp