SM_CTRL: TL_SharedMemoryWrapper Class Reference
TL_SharedMemoryWrapper Class Reference
Работа с разделяемой памятью
#include <TL_SharedMemoryWrapper.h>
Classes
struct BufPtr
Структура указателя на один буфер
Public Member Functions
TL_SharedMemoryWrapper (char *fname, int sizeOfBytes)
~TL_SharedMemoryWrapper ()
void * GetPtr (void)
Получение указателя на память
Private Member Functions
void FreeSharedMemory (void)
Освобождение памяти
Private Attributes
HANDLE m_handleMemory
Параметры стрима
int m_SizeOfBytes
Размер области памяти в байтах
BufPtr m_PtrBuf [1]
Массив указателей на буфера
Detailed Description
Работа с разделяемой памятью
Работа с общей памятью
Definition at line 10 of file TL_SharedMemoryWrapper.h.
Constructor & Destructor Documentation
TL_SharedMemoryWrapper()
TL_SharedMemoryWrapper::TL_SharedMemoryWrapper (char * fname, int sizeOfBytes)
Definition at line 9 of file TL_SharedMemoryWrapper.cpp.
References TL_SharedMemoryWrapper::BufPtr::handle, m_PtrBuf, m_SizeOfBytes, and TL_SharedMemoryWrapper::BufPtr::ptr.
~TL_SharedMemoryWrapper()
TL_SharedMemoryWrapper::~TL_SharedMemoryWrapper ()
Definition at line 42 of file TL_SharedMemoryWrapper.cpp.
References FreeSharedMemory().
Member Function Documentation
FreeSharedMemory()
void TL_SharedMemoryWrapper::FreeSharedMemory (void) private
Освобождение памяти
Definition at line 53 of file TL_SharedMemoryWrapper.cpp.
References TL_SharedMemoryWrapper::BufPtr::clear(), and m_PtrBuf.
Referenced by ~TL_SharedMemoryWrapper().
GetPtr()
void * TL_SharedMemoryWrapper::GetPtr (void)
Получение указателя на память
Definition at line 67 of file TL_SharedMemoryWrapper.cpp.
References m_PtrBuf, and TL_SharedMemoryWrapper::BufPtr::ptr.
Referenced by TF_SimulinkShared::TF_SimulinkShared().
Member Data Documentation
m_handleMemory
HANDLE TL_SharedMemoryWrapper::m_handleMemory private
Параметры стрима
Definition at line 16 of file TL_SharedMemoryWrapper.h.
m_PtrBuf
BufPtr TL_SharedMemoryWrapper::m_PtrBuf[1] private
Массив указателей на буфера
Definition at line 51 of file TL_SharedMemoryWrapper.h.
Referenced by FreeSharedMemory(), GetPtr(), and TL_SharedMemoryWrapper().
m_SizeOfBytes
int TL_SharedMemoryWrapper::m_SizeOfBytes private
Размер области памяти в байтах
Definition at line 48 of file TL_SharedMemoryWrapper.h.
Referenced by TL_SharedMemoryWrapper().
The documentation for this class was generated from the following files:
E:/_github/simulink_sm/simulink_sm/src/low/device/TL_SharedMemoryWrapper.h
E:/_github/simulink_sm/simulink_sm/src/low/device/TL_SharedMemoryWrapper.cpp