SM_CTRL: TF_SimulinkShared Class Reference
TF_SimulinkShared Class Reference
Обмен между Simulink и ADC через разделяемую память
#include <TF_SimulinkShared.h>
Public Member Functions
TF_SimulinkShared (char *fname)
~TF_SimulinkShared ()
U32 GetFlag (U32 id)
Получение флага из разделяемой памяти
U32 SetFlag (U32 id, U32 val)
Установка флага в разделяемой памяти
U32 * GetBuf (void)
Получение указателя на буфер
double SetDoubleParam (U32 id, double val)
Установка параметра типа double в разделяемой памяти
double GetDoubleParam (U32 id)
Чтение параметра типа double из разделяемой памяти
Private Attributes
TL_SharedMemoryWrapper * m_pSharedMemory
U32 * m_pBufParam
Указатель на буфер параметров
U32 * m_pBufData
Указатель на буфер данных
double * m_pBufDoubleParam
Указатель на область параметров типа double.
Detailed Description
Обмен между Simulink и ADC через разделяемую память
Definition at line 8 of file TF_SimulinkShared.h.
Constructor & Destructor Documentation
TF_SimulinkShared()
TF_SimulinkShared::TF_SimulinkShared (char * fname)
Definition at line 7 of file TF_SimulinkShared.cpp.
References TL_SharedMemoryWrapper::GetPtr(), m_pBufData, m_pBufDoubleParam, m_pBufParam, and m_pSharedMemory.
~TF_SimulinkShared()
TF_SimulinkShared::~TF_SimulinkShared ()
Definition at line 18 of file TF_SimulinkShared.cpp.
References m_pSharedMemory.
Member Function Documentation
GetBuf()
U32 * TF_SimulinkShared::GetBuf (void)
Получение указателя на буфер
Definition at line 39 of file TF_SimulinkShared.cpp.
References m_pBufData.
Referenced by Block::outputs().
GetDoubleParam()
double TF_SimulinkShared::GetDoubleParam (U32 id)
Чтение параметра типа double из разделяемой памяти
Definition at line 54 of file TF_SimulinkShared.cpp.
References m_pBufDoubleParam.
GetFlag()
U32 TF_SimulinkShared::GetFlag (U32 id)
Получение флага из разделяемой памяти
Definition at line 24 of file TF_SimulinkShared.cpp.
References m_pBufParam.
Referenced by Block::outputs(), and Block::start().
SetDoubleParam()
double TF_SimulinkShared::SetDoubleParam (U32 id, double val)
Установка параметра типа double в разделяемой памяти
Definition at line 46 of file TF_SimulinkShared.cpp.
References m_pBufDoubleParam.
SetFlag()
U32 TF_SimulinkShared::SetFlag (U32 id, U32 val)
Установка флага в разделяемой памяти
Definition at line 31 of file TF_SimulinkShared.cpp.
References m_pBufParam.
Referenced by Block::outputs(), and Block::start().
Member Data Documentation
m_pBufData
U32* TF_SimulinkShared::m_pBufData private
Указатель на буфер данных
Definition at line 17 of file TF_SimulinkShared.h.
Referenced by GetBuf(), and TF_SimulinkShared().
m_pBufDoubleParam
double* TF_SimulinkShared::m_pBufDoubleParam private
Указатель на область параметров типа double.
Definition at line 20 of file TF_SimulinkShared.h.
Referenced by GetDoubleParam(), SetDoubleParam(), and TF_SimulinkShared().
m_pBufParam
U32* TF_SimulinkShared::m_pBufParam private
Указатель на буфер параметров
Definition at line 14 of file TF_SimulinkShared.h.
Referenced by GetFlag(), SetFlag(), and TF_SimulinkShared().
m_pSharedMemory
TL_SharedMemoryWrapper* TF_SimulinkShared::m_pSharedMemory private
Definition at line 11 of file TF_SimulinkShared.h.
Referenced by TF_SimulinkShared(), and ~TF_SimulinkShared().
The documentation for this class was generated from the following files:
E:/_github/simulink_sm/simulink_sm/src/low/device/TF_SimulinkShared.h
E:/_github/simulink_sm/simulink_sm/src/low/device/TF_SimulinkShared.cpp